Update old_aidant_deactivation_warning.txt
betagouv/Aidants_Connect pull request #1022
Opened 2023-10-05 13:02 UTC by matteo-goracci

Mettre à jour l'e-mail qui vise à prévenir l'aidant de la désactivation prochaine de son compte.

## 🌮 Objectif

- Mettre en avant qu'il suffit de se connecter pour maintenir son compte. 

- Eviter les inscriptions “forcées” par mauvaise interprétation du mail

2023-10-09 07:53 UTC, mrjmad approved these changes

2023-10-09 08:55 UTC, christophehenry commented
Faut mettre à jour le MJML correspondant, aussi.

2023-10-09 08:56 UTC, christophehenry requested changes

2023-10-09 08:56 UTC, christophehenry commented on aidants_connect_web/templates/email/old_aidant_deactivation_warning.txt
> -
Faut mettre à jour le MJML correspondant, aussi.

2023-10-10 08:33 UTC, christophehenry approved these changes

2023-10-10 09:34 UTC, merged