Intégration des nouvelles pages habilitation et formation du site public, DSR style
betagouv/Aidants_Connect pull request #1225
Opened 2024-04-08 12:16 UTC by MarjolaineLB

## 🌮 Objectif

Intégration des nouvelles pages habilitation et formation du site public, DSR style

## 🔍 Implémentation

création d'une nouvelle page/url formation
refonte de la page habilitation

## 🖼️ Images
![image](https://github.com/betagouv/Aidants_Connect/assets/19302155/d6e76f25-84d7-4f87-86cd-49e2809b2656)
![319675235-4c325df0-4fdf-41d0-94da-659774ce1baa](https://github.com/betagouv/Aidants_Connect/assets/19302155/5fc09353-ecd8-4d71-b066-c7ac5a8128e7)

2024-04-08 12:27 UTC, mrjmad approved these changes

2024-04-08 12:54 UTC, christophehenry requested changes

2024-04-08 12:54 UTC, christophehenry commented on aidants_connect_web/urls.py
>      path("habilitation", service.habilitation, name="habilitation"),
```suggestion
    path("formation", service.formation, name="habilitation_faq_formation"),
    path("habilitation", service.habilitation, name="habilitation_faq_habilitation"),
```

2024-04-09 07:37 UTC, christophehenry approved these changes

2024-04-09 07:58 UTC, merged