Annulation de la requête d'habilitation depuis la page habilitation
betagouv/Aidants_Connect pull request #1226
Opened 2024-04-08 12:21 UTC by christophehenry

## 🌮 Objectif

Annulation de la requête d'habilitation depuis la page habilitation

2024-04-08 12:39 UTC, christophehenry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter un bouton "annuler la demande d'habilitation" sur les cartes aidant, dans la page résumé demande d'habilitation](https://trello.com/c/aGMjZ2wd/552-ajouter-un-bouton-annuler-la-demande-dhabilitation-sur-les-cartes-aidant-dans-la-page-r%C3%A9sum%C3%A9-demande-dhabilitation)

2024-04-09 07:43 UTC, mrjmad reviewed
ca m'a l'air ok , je déploie en integ des que possible pour tester puis ca aprt en merge

2024-04-09 13:17 UTC, mrjmad requested changes

2024-04-09 13:17 UTC, mrjmad commented on aidants_connect_habilitation/templates/cancel-habilitation-request.html
> +      <h1>Annuler la demande de formation</h1>
remplacer formation par "demande habilitation"

2024-04-09 13:17 UTC, mrjmad commented on aidants_connect_habilitation/templates/cancel-habilitation-request.html
> +        <p>Confirmez-vous l’annulation de la demande de formation pour ce profil ?</p>
remplacer formation par "demande habilitation"

2024-04-09 13:17 UTC, mrjmad commented on aidants_connect_habilitation/templates/_display_org_request.html
> +            </a>
mettre un petit statut "annulé" si c'est annulé

2024-04-09 14:08 UTC, merged