intégration des nouvelles pages de cgu et politique de confidentialité
betagouv/Aidants_Connect pull request #1243
Opened 2024-04-15 16:25 UTC by MarjolaineLB

## 🌮 Objectif

Intégration des nouvelles pages Conditions générales d'utilisation et Politique de confidentialité

## 🔍 Implémentation

- 1 page totalement refaite et 1 nouvellepage

## 🖼️ Images
![image](https://github.com/betagouv/Aidants_Connect/assets/19302155/0d09dd13-b5a6-4745-84af-a9d5a3ee7953)
![image](https://github.com/betagouv/Aidants_Connect/assets/19302155/15928fa6-d0c8-4eee-bc17-dbf084723e0f)

2024-04-16 08:19 UTC, christophehenry requested changes

2024-04-16 08:19 UTC, christophehenry commented on aidants_connect_common/static/css/common.css
> +}
```suggestion
.fr-text-default {
  color: var(--text-default-grey);
}
```

Pour permettre l'utilisation potentielle d'un thème sombre.

À mettre dans [la section utils de `aidants_connect_common/static/scss/main.scss`](https://github.com/betagouv/Aidants_Connect/blob/main/aidants_connect_common/static/scss/main.scss#L87). C'est ce fichier qui donne le design commun. Tu peux utiliser `python manage.py scss --watch` pour compiler le SCSS.

2024-04-16 08:19 UTC, christophehenry commented on aidants_connect_common/static/css/common.css
> +}
Je propose de modifier plutôt [la règle définie dans `main.scss`](https://github.com/betagouv/Aidants_Connect/blob/main/aidants_connect_common/static/scss/main.scss#L16).

2024-04-16 08:19 UTC, christophehenry commented on aidants_connect_common/templates/public_website/layout/layout_cgu.html
> +{% endblock extracss %}
Il devrait pas y avoir besoin de ce fichier CSS, si ? C'est essentiellement des règles legacy. Je pense même que tu peux le supprimer.

2024-04-16 08:19 UTC, christophehenry commented on aidants_connect_web/templates/public_website/politique_confidentialite.html
> +      <p>Pour les exercer, contactez-nous à : <a href="mailto:contact@aidantsconnect.beta.gouv.fr" class="fr-link" target="_blank">contact@aidantsconnect.beta.gouv.fr</a></p>
```suggestion
      <p>Pour les exercer, contactez-nous à : {% mailto_href AC_CONTACT_EMAIL %}</p>
```

Faudra `{% load ac_common %}` aussi.

2024-04-16 08:19 UTC, christophehenry commented on aidants_connect_web/templates/public_website/politique_confidentialite.html
> +{% endblock body %}
Est-ce que tu peux mettre un `&nbsp;` devant tous les deux-points, points d'exclamation et points d'interrogation ?

2024-04-16 10:00 UTC, MarjolaineLB commented on aidants_connect_common/static/css/common.css
> +}
ça correspond à du css que j'avais initié pour la page des mandats. 
Je l'ai laissé.
Tu préfères que je le supprime et le remette pour la PR sur les mandats ?

2024-04-16 10:02 UTC, MarjolaineLB commented on aidants_connect_common/static/css/common.css
> +}
absolument je supprime

2024-04-16 10:05 UTC, MarjolaineLB commented on aidants_connect_common/static/css/common.css
> +}
je pensais qu'on voulait se débarrasser du SCSS ?

2024-04-16 10:05 UTC, MarjolaineLB commented on aidants_connect_common/static/css/common.css
> +}
je n'ai pas osé car c'est sûrement utilisé ailleurs, non ?

2024-04-16 10:05 UTC, MarjolaineLB commented on aidants_connect_web/templates/public_website/politique_confidentialite.html
> +      <p>Pour les exercer, contactez-nous à : <a href="mailto:contact@aidantsconnect.beta.gouv.fr" class="fr-link" target="_blank">contact@aidantsconnect.beta.gouv.fr</a></p>
👍

2024-04-16 10:30 UTC, christophehenry commented on aidants_connect_common/static/css/common.css
> +}
Oui, c'est mieux. Quoi qu'il arrive, mets tout dans `main.scss`

2024-04-16 10:31 UTC, christophehenry commented on aidants_connect_common/static/css/common.css
> +}
Quand c'est pas nécessaire, oui. Mais dans `main.scss`, j'utilise des fonctions Sass.

2024-04-16 10:32 UTC, christophehenry commented on aidants_connect_common/static/css/common.css
> +}
Je pense pas. C'est du CSS que j'ai recopié du design précédent.

2024-04-16 10:34 UTC, christophehenry commented on aidants_connect_web/templates/public_website/politique_confidentialite.html
> +{% endblock body %}
Pour éviter un retour à la ligne avant les ponctuation.

2024-04-17 08:43 UTC, christophehenry requested changes

2024-04-17 08:43 UTC, christophehenry commented on aidants_connect_web/static/css/habilitation.css
>  .fr-info-text {
Je pense que tu peux carrément supprimer ce fichier. Il est utilisé par [`layout_habilitation.html`](aidants_connect_common/templates/public_website/layout/layout_habilitation.html) mais j'ai l'impression que c'est que du style legacy. Tu peux confirmer que ça casse pas `layout_habilitation.html` et supprimer le cas échéant ?

2024-04-17 08:43 UTC, christophehenry commented on aidants_connect_web/templates/public_website/politique_confidentialite.html
> +      <p>Pour les exercer, contactez-nous à&nbsp;: <a href="{% mailto_href AC_CONTACT_EMAIL %}" class="fr-link" target="_blank">contact@aidantsconnect.beta.gouv.fr</a></p>
```suggestion
      <p>Pour les exercer, contactez-nous à&nbsp;: {% mailto AC_CONTACT_EMAIL %}</p>
```

Pardon, je t'ai donné le mauvais code lors de la dernière revue. `{% mailto %}` génère automatiquement le `<a>`.

2024-04-17 08:43 UTC, christophehenry commented on aidants_connect_web/templates/public_website/politique_confidentialite.html
> +      <p>Pour vous aider dans votre démarche, vous trouverez un modèle de courrier élaboré par la CNIL ici&nbsp;: <a href="https://www.cnil.fr/fr/modele/courrier/exercer-son-droit-dacces" target="_bl
```suggestion
      <p>Pour vous aider dans votre démarche, vous trouverez un modèle de courrier élaboré par la CNIL ici&nbsp;: <a href="https://www.cnil.fr/fr/modele/courrier/exercer-son-droit-dacces" target="_blank" rel="noopener noreferer" class="fr-link">https://www.cnil.fr/fr/modele/courrier/exercer-son-droit-dacces</a></p>
```

Pro-tips sécurité : Toujours utiliser `rel="noopener noreferer"` avec un `target="_blank"` : https://techstacker.com/html-noopener-attribute/

2024-04-17 08:43 UTC, christophehenry commented on aidants_connect_web/templates/public_website/politique_confidentialite.html
> +              <td><a href="https://scalingo.com/fr/contrat-gestion-traitements-donnees-personnelles" class="fr-link fr-text--sm" target="_blank">https://scalingo.com/fr/contrat-gestion-traitements-do
```suggestion
              <td><a href="https://scalingo.com/fr/contrat-gestion-traitements-donnees-personnelles" class="fr-link fr-text--sm" target="_blank" rel="noopener noreferer">https://scalingo.com/fr/contrat-gestion-traitements-donnees-personnelles</a></td>
```

2024-04-17 08:43 UTC, christophehenry commented on aidants_connect_web/templates/public_website/politique_confidentialite.html
> +              <td><a href="https://policies.google.com/privacy?hl=fr" class="fr-link fr-text--sm" target="_blank">https://policies.google.com/privacy?hl=fr</a></td>
`rel="noopener noreferer"`

2024-04-17 08:50 UTC, MarjolaineLB commented on aidants_connect_web/static/css/habilitation.css
>  .fr-info-text {
non non il ne faut pas supprimer ce fichier. Sur la page habilitation, il y a 2 trois trucs customs (notamment les ronds bleus avec les nombres de mémoire)

2024-04-17 08:54 UTC, MarjolaineLB commented on aidants_connect_web/templates/public_website/politique_confidentialite.html
> +              <td><a href="https://policies.google.com/privacy?hl=fr" class="fr-link fr-text--sm" target="_blank">https://policies.google.com/privacy?hl=fr</a></td>
effectivement je connaissais ce tips en plus. My bad

2024-04-17 08:56 UTC, MarjolaineLB commented on aidants_connect_web/templates/public_website/politique_confidentialite.html
> +      <p>Pour les exercer, contactez-nous à&nbsp;: <a href="{% mailto_href AC_CONTACT_EMAIL %}" class="fr-link" target="_blank">contact@aidantsconnect.beta.gouv.fr</a></p>
si je ne mets que `{% mailto %}` ça me déclenche une erreur 
 ```
 TemplateSyntaxError at /cgu/

'mailto' did not receive value(s) for the argument(s): 'recipient'
 ```

2024-04-17 09:05 UTC, christophehenry approved these changes

2024-04-17 09:30 UTC, merged