Ajout d'un champs d'état aux formations et inscrits aux formations
betagouv/Aidants_Connect pull request #1281
Opened 2024-05-06 09:47 UTC by christophehenry

## 🌮 Objectif

Ajout d'un champs d'état aux formations et inscrits aux formations

2024-05-06 09:47 UTC, christophehenry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter un statut dans les session de formation "active / annulée" (deux choix pour l'instant mais peutre plus après )](https://trello.com/c/eBNWBolG/600-ajouter-un-statut-dans-les-session-de-formation-active-annul%C3%A9e-deux-choix-pour-linstant-mais-peutre-plus-apr%C3%A8s)

2024-05-06 09:48 UTC, christophehenry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajouter un statut dans les inscriptions d'aidant Validée (par défaut) / Liste d'attente / Annulée)](https://trello.com/c/zXcIeDlL/601-ajouter-un-statut-dans-les-inscriptions-daidant-valid%C3%A9e-par-d%C3%A9faut-liste-dattente-annul%C3%A9e)

2024-05-07 06:58 UTC, mrjmad requested changes
erreur de copier / coller sur le label

2024-05-07 06:58 UTC, mrjmad commented on aidants_connect_common/models.py
> +        "En présentiel/à distance", choices=State.choices, default=State.ACTIVE
le label va pas ici

2024-05-07 06:58 UTC, mrjmad commented on aidants_connect_common/models.py
> +    state = models.IntegerField(
le label va pas

2024-05-07 07:37 UTC, christophehenry commented on aidants_connect_common/models.py
> +    state = models.IntegerField(
Done

2024-05-07 08:54 UTC, mrjmad approved these changes

2024-05-07 09:59 UTC, merged