Dsfr creer un mandat
betagouv/Aidants_Connect pull request #1307
Opened 2024-05-21 07:42 UTC by MarjolaineLB

## 🌮 Objectif

_Un petit résumé de l'objectif de la PR en 1 ligne_

## 🔍 Implémentation

- _Une liste des modifications_

## 🏕 Amélioration continue

- _(optionnel) Une liste d'autres modifications pas en lien direct avec la PR_

## ⚠️ Informations supplémentaires

_(optionnel) Documentation, commandes à lancer, variables d'environment, etc_

## 🖼️ Images

_(optionnel) Une ou plusieurs captures d'écran_

2024-05-29 08:46 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/new_mandat/new_mandat.html
> +{% extends 'public_website/layout/main.html' %}
```suggestion
{% extends 'layout/main.html' %}
```

Non ?

2024-05-29 09:33 UTC, MarjolaineLB commented on aidants_connect_web/templates/aidants_connect_web/new_mandat/new_mandat.html
> +{% extends 'public_website/layout/main.html' %}
non plutôt `{% extends 'layouts/main.html' %}`

2024-06-05 08:25 UTC, christophehenry commented on aidants_connect_common/templates/fields/checkbox_fr_grid_row.html
> +  <div class="fr-col-12 checkbox-col fr-checkbox-group">
Idéalement, plutôt que de le modifier, on aimerait supprimer ce template plutôt que de le réutiliser puisque `django-dsfr` a ses propres templates pour afficher les formulaire et ses champs.

2024-06-05 08:32 UTC, christophehenry commented on aidants_connect_common/templatetags/form_extras.py
> +
En fait on veut plutôt se débarrasser de ces balises et les remplacer par [`dsfr_form`](https://numerique-gouv.github.io/django-dsfr/components/form/) et [`dsfr_form_field`](https://numerique-gouv.github.io/django-dsfr/components/form_field/) que d'en créer de nouvelles.

2024-06-05 08:33 UTC, christophehenry commented on aidants_connect_web/templates/widgets/mandat-duree-radio-option.html
> +  <div class="fr-radio-group">
Y'a pas une erreur, ici ?

2024-06-05 08:51 UTC, christophehenry requested changes

2024-06-05 08:51 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/new_mandat/new_mandat_recap.html
> +          </label>
Ici, je préfère qu'on utilise `{% dsfr_form %}`.

Et il faudra modifier `RecapMandatForm` comme ça :

```py
class RecapMandatForm(OTPForm):
    personal_data = forms.BooleanField()

    def __init__(self, aidant, *args, **kwargs):
        super().__init__(aidant, *args, **kwargs)
        self.fields["personal_data"].label = mark_safe(
            f"Avoir communiqué à <strong>{self.aidant.get_full_name()}</strong> les "
            "informations concernant l’objet de l’intervention, la raison pour "
            "laquelle ses informations sont collectées et leur utilité ; les droits "
            "sur ses données ET avoir conservé son consentement écrit "
            "(capture d'écran email, SMS…) pour conclure le mandat et utiliser ses "
            "données à caractère personnel."
        )
```

2024-06-19 10:20 UTC, christophehenry commented on aidants_connect/settings.py
> +MANDAT_TEMPLATE_CURRENT_FILE = "20240618_mandat.html"
Pourquoi on a besoin de changer le template du mandat ? :thinking:

2024-06-19 10:23 UTC, christophehenry commented on aidants_connect_common/forms.py
> +class PatchedForm(Form, WidgetAttrMixin):
Je préfère ne pas toucher à cette classe parce que je sais pas dans quelle mesure ça pourrait casser le design des pages existantes et, de toutes façons, cette classe va sauter et être en partie remplacée par `DsfrBaseForm` et [`ErrorCodesManipulationMixin`](https://github.com/betagouv/Aidants_Connect/pull/1307/commits/6a8d928eddf01c3d86b65dd27892b69a7c962c8e#diff-198e7e774d1b2a77eadf5acbe78b68b210fceba6a9725123924771f207a4c85fR65)

2024-06-19 10:41 UTC, MarjolaineLB commented on aidants_connect/settings.py
> +MANDAT_TEMPLATE_CURRENT_FILE = "20240618_mandat.html"
parce que la formulation a changé. Les "à la place de" sont remplacés par "pour le compte de"

2024-06-19 11:53 UTC, christophehenry commented on aidants_connect/settings.py
> +MANDAT_TEMPLATE_CURRENT_FILE = "20240618_mandat.html"
Ok

2024-06-19 12:20 UTC, christophehenry commented on aidants_connect_common/tests/test_functionnal/test_personnel_form.py
> +
Cette partie-là n'a rien à voir avec ton code. C'est juste qu'on a un test qui casse aléatoirement donc j'essaie de le fiabiliser. On verra si ça tient.

2024-06-19 12:45 UTC, MarjolaineLB commented on aidants_connect_common/tests/test_functionnal/test_personnel_form.py
> +
ah ok, je comprenais vraiment pas l'erreur de test. Merci

2024-06-20 07:18 UTC, christophehenry commented on aidants_connect_common/tests/test_functionnal/test_personnel_form.py
> +
En gros, dans une autre partie du code, on a un bouton qui ouvre une modale. `_open_modale` clique sur ce bouton pour ouvrir la modale et patiente jusqu'à ce qu'elle soit ouverte. Dans certaines circonstances que je comprends pas, cette méthode est appelée alors que la modale est déjà ouverte et cache le bouton d'ouverture de modale. Selenium s'offusque alors de pas pouvoir cliquer sur le bouton parce qu'il est caché par la modale. Donc pour tenter de fiabiliser ce test, j'ai je vérifie si la modale est déjà ouverte avant d'essayer de cliquer sur le bouton. On va voir si ça fonctionne.

2024-06-20 08:29 UTC, MarjolaineLB commented on aidants_connect_web/views/mandat.py
aaaah c'est ça qui me manquait :)

2024-06-24 09:34 UTC, christophehenry approved these changes

2024-06-24 14:51 UTC, merged