Ajouts de filtres, colonne, critere de recherche pour l'admin formation / inscription formation
betagouv/Aidants_Connect pull request #1353
Opened 2024-07-14 16:20 UTC by mrjmad

## 🌮 Objectif

Ajouts de filtres, colonne, critere de recherche pour l'admin formation / inscription formation

## 🔍 Implémentation

- _Une liste des modifications_

## 🏕 Amélioration continue

- _(optionnel) Une liste d'autres modifications pas en lien direct avec la PR_

## ⚠️ Informations supplémentaires

_(optionnel) Documentation, commandes à lancer, variables d'environment, etc_

## 🖼️ Images

_(optionnel) Une ou plusieurs captures d'écran_

2024-07-14 17:20 UTC, christophehenry requested changes

2024-07-14 17:20 UTC, christophehenry commented on aidants_connect_common/admin.py
> +    def get_formation_type_labe(self, obj):
```suggestion
    def get_formation_type_label(self, obj):
```

2024-07-18 07:25 UTC, christophehenry approved these changes

2024-07-18 07:25 UTC, Lycia-r approved these changes

2024-07-19 06:58 UTC, merged