Dsfr recap demande
betagouv/Aidants_Connect pull request #1415
Opened 2024-09-11 16:55 UTC by MarjolaineLB

## 🌮 Objectif

Nouvelle de récapitulatif de la demande d'habilitation - DSFR

## 🖼️ Images

![image](https://github.com/user-attachments/assets/e940ac64-b082-4aa5-8c29-ee2be9bc6af6)

2024-09-17 10:04 UTC, christophehenry commented on aidants_connect_common/static/scss/main.scss
> +}
C'est pas utile, tu peux supprimer.

2024-09-17 10:15 UTC, christophehenry requested changes

2024-09-17 10:15 UTC, christophehenry commented on aidants_connect_common/static/scss/main.scss
> +}
C'est pas utile, tu peux supprimer (voir les autres commentaires)

2024-09-17 10:15 UTC, christophehenry commented on aidants_connect_habilitation/templates/_recap_general_info.html
> +      {% if show_edit_buttons %}
```suggestion
```

Ce block `if` semble toujours vrai.

2024-09-17 10:15 UTC, christophehenry commented on aidants_connect_habilitation/templates/_recap_general_info.html
> +      {% endif %}
```suggestion
```

2024-09-17 10:15 UTC, christophehenry commented on aidants_connect_habilitation/templates/_recap_general_info.html
> +      </div>
```suggestion
          <ul class="fr-btns-group fr-btns-group--sm fr-btns-group--right fr-btns-group--inline">
            <li>
              <a
                class="fr-btn fr-btn--tertiary fr-btn--icon fr-icon-pencil-fill"
                href="{% url 'habilitation_modify_organisation' issuer_id=issuer.issuer_id uuid=organisation.uuid %}"
              >
                Éditer
              </a>
            </li>
          </ul>
```

Voir [les groupes de bouton du DSFR](https://www.systeme-de-design.gouv.fr/composants-et-modeles/groupe-de-boutons).

2024-09-17 10:15 UTC, christophehenry commented on aidants_connect_habilitation/templates/_recap_general_info.html
> +        </div>
```suggestion
          <ul class="fr-btns-group fr-btns-group--sm fr-btns-group--right fr-btns-group--inline">
            <li>
            <a
              class="fr-btn fr-btn--tertiary fr-btn--icon fr-icon-pencil-fill"
              href="{% url 'habilitation_modify_issuer' issuer_id=issuer.issuer_id %}"
            >
              Éditer
            </a>
            </li>
          </ul>
```

Voir [les groupes de bouton du DSFR](https://www.systeme-de-design.gouv.fr/composants-et-modeles/groupe-de-boutons).

2024-09-17 10:15 UTC, christophehenry commented on aidants_connect_habilitation/templates/validation_form.html
> +    {% include '_recap_general_info.html' with show_edit_buttons=True %}
Tu peux rapatrier le code de ce partial ici. Il ne semble pas utilisé ailleurs.

2024-09-17 10:15 UTC, christophehenry commented on aidants_connect_habilitation/templates/validation_form.html
> +      <div class="fr-grid-row fr-grid-row--gutters fr-mb-4v background-grey fr-p-3w">
```suggestion
      <div class="fr-grid-row fr-grid-row--gutters fr-mb-4v fr-background-default--grey fr-p-3w">
```

Le DSFR frournit déjà des classes utils `fr-background-*`.

2024-09-17 10:24 UTC, MarjolaineLB commented on aidants_connect_habilitation/templates/_recap_general_info.html
> +      {% if show_edit_buttons %}
pour le moment, oui, mais j'anticipe sur les pages pour retourner voir l'état de sa demande qui arrivent derrière

2024-09-17 10:25 UTC, MarjolaineLB commented on aidants_connect_habilitation/templates/validation_form.html
> +    {% include '_recap_general_info.html' with show_edit_buttons=True %}
il le sera dans les pages pour retourner voir sa demande

2024-09-17 15:44 UTC, MarjolaineLB commented on aidants_connect_habilitation/templates/_recap_general_info.html
> +      </div>
pourquoi un groupe de bouton ?

2024-09-18 07:44 UTC, christophehenry requested changes

2024-09-18 07:44 UTC, christophehenry commented on aidants_connect_habilitation/templates/_recap_general_info.html
> +            <div class="fr-col-12 fr-col-md-6 fr-mb-2w">{% if organisation.is_private_org  %}Oui {% else %}Non {% endif %}</div>
```suggestion
            <div class="fr-col-12 fr-col-md-6 fr-mb-2w">{{ organisation.is_private_org|yesno:"Oui,Non" }}</div>
```

2024-09-18 07:44 UTC, christophehenry commented on aidants_connect_habilitation/templates/_recap_general_info.html
> +            <div class="fr-col-12 fr-col-md-6 fr-mb-2w">{% if organisation.france_services_label  %}Oui {% else %}Non {% endif %}</div>
```suggestion
            <div class="fr-col-12 fr-col-md-6 fr-mb-2w">{{ organisation.france_services_label|yesno:"Oui,Non" }}</div>
```

2024-09-18 07:44 UTC, christophehenry commented on aidants_connect_web/static/css/recap_habilitations.css
> +}
Ce fichier ne semble plus utilisé. Je pense que tu peux le supprimer.

2024-09-18 09:42 UTC, christophehenry approved these changes

2024-09-18 10:05 UTC, merged