nouvelle integration page structure
betagouv/Aidants_Connect pull request #1455
Opened 2024-11-19 10:54 UTC by MarjolaineLB

## 🌮 Objectif
Passage de la page Structure du Formulaire d'Habilitation au DSFR

## 🖼️ Images

![image](https://github.com/user-attachments/assets/25e68b15-9057-48b0-a5e8-419c2b3d8ad2)

2024-11-19 17:40 UTC, christophehenry requested changes

2024-11-25 08:16 UTC, MarjolaineLB commented on aidants_connect_habilitation/templates/organisation_form.html
> +        <form method="post" class="fr-my-8v">
@christophehenry très compliqué de faire ça en respectant les maquettes, notamment, les titres, sous-titres, tailles de colonne

2024-11-25 10:09 UTC, christophehenry commented on aidants_connect_habilitation/templates/organisation_form.html
> +        <form method="post" class="fr-my-8v">
Tu peux partir sur un truc comme ça :

```diff
diff --git a/aidants_connect_habilitation/forms.py b/aidants_connect_habilitation/forms.py
index 5b945030..8593778c 100644
--- a/aidants_connect_habilitation/forms.py
+++ b/aidants_connect_habilitation/forms.py
@@ -17,6 +17,7 @@ from django.forms import (
     TextInput,
     TypedChoiceField,
     modelformset_factory,
+    Media,
 )
 from django.forms.formsets import MAX_NUM_FORM_COUNT, TOTAL_FORM_COUNT
 from django.urls import reverse
@@ -34,8 +35,10 @@ from aidants_connect_common.forms import (
     PatchedErrorList,
     PatchedForm,
     PatchedModelForm,
+    WidgetAttrMixin,
 )
 from aidants_connect_common.utils.gouv_address_api import Address, search_adresses
+from aidants_connect_common.widgets import JSModulePath
 from aidants_connect_habilitation import models
 from aidants_connect_habilitation.models import (
     AidantRequest,
@@ -47,7 +50,7 @@ from aidants_connect_habilitation.models import (
 from aidants_connect_web.models import OrganisationType
 
 
-class AddressValidatableMixin(Form):
+class AddressValidatableMixin(Form, WidgetAttrMixin):
     DEFAULT_CHOICE = "DEFAULT"
 
     # Necessary so dynamically setting properties
@@ -198,9 +201,9 @@ class IssuerForm(ModelForm, CleanEmailMixin, DsfrBaseForm):
         exclude = ["issuer_id", "email_verified"]
 
 
-class OrganisationRequestForm(
-    DsfrBaseForm, AddressValidatableMixin, CleanZipCodeMixin
-):
+class OrganisationRequestForm(DsfrBaseForm, AddressValidatableMixin, CleanZipCodeMixin):
+    template_name = "aidants_connect_habilitation/forms/organisation-request.html"
+
     type = ChoiceField(
         required=True, choices=RequestOriginConstants.choices, label="Type de structure"
     )
@@ -248,29 +251,9 @@ class OrganisationRequestForm(
         required=False,
     )
 
-    def __init__(self, *args, **kwargs):
-        super().__init__(*args, **kwargs)
-        self.widget_attrs(
-            "type",
-            {
-                "data-action": "change->dynamic-form#onTypeChange",
-                "data-dynamic-form-target": "typeInput",
-            },
-        )
-        self.widget_attrs(
-            "is_private_org",
-            {
-                "data-action": "change->dynamic-form#onIsPrivateOrgChange",
-                "data-dynamic-form-target": "privateOrgInput",
-            },
-        )
-        self.widget_attrs(
-            "france_services_label",
-            {
-                "data-action": "change->dynamic-form#onFranceServicesChange",
-                "data-dynamic-form-target": "franceServicesInput",
-            },
-        )
+    @property
+    def media(self):
+        return Media(js=(JSModulePath("js/organisation-form.mjs"),))
 
     def clean_type(self):
         return OrganisationType.objects.get(pk=int(self.data["type"]))
diff --git a/aidants_connect_habilitation/templates/aidants_connect_habilitation/forms/organisation-request.html b/aidants_connect_habilitation/templates/aidants_connect_habilitation/forms/organisation-request.html
new file mode 100644
index 00000000..7508bfe8
--- /dev/null
+++ b/aidants_connect_habilitation/templates/aidants_connect_habilitation/forms/organisation-request.html
@@ -0,0 +1,119 @@
+{% load ac_common %}
+{% load dsfr_tags widget_tweaks %}
+<form
+  method="post"
+  class="fr-my-8v"
+  data-controller="dynamic-form"
+  data-dynamic-form-type-other-value="{{ type_other_value }}"
+>
+  {% csrf_token %}
+
+  <fieldset class="fr-fieldset">
+    <legend class="fr-fieldset__legend">Informations générales</legend>
+    <div class="fr-fieldset__element">
+      <p>Vous pouvez faire autant de demandes qu’il existe de structures d’accueil.</p>
+    </div>
+
+    <div class="fr-fieldset__element">
+      {% dsfr_form_field form.type|attr:"data-action:change->dynamic-form#onTypeChange"|attr:"data-dynamic-form-target:typeInput" %}
+    </div>
+
+    <div class="fr-fieldset__element" data-dynamic-form-target="typeOtherInputContainer">
+      {% dsfr_form_field form.type_other %}
+    </div>
+
+    <div class="fr-fieldset__element">{% dsfr_form_field form.france_services_label|attr:"data-action:change->dynamic-form#onFranceServicesChange"|attr:"data-dynamic-form-target:franceServicesInput" %}</div>
+    <div class="fr-fieldset__element">{% dsfr_form_field form.name %}</div>
+    <div class="fr-fieldset__element">{% dsfr_form_field form.siret %}</div>
+
+    <p>
+      <em>Besoin d’aide pour retrouver votre SIRET ?</em>
+      <a
+        class="fr-link fr-link--icon-right fr-icon-arrow-right-line"
+        href="https://annuaire-entreprises.data.gouv.fr/?mtm_campaign=aidants_connect"
+      >
+        Annuaire des Entreprises
+      </a>
+    </p>
+  </fieldset>
+
+  <fieldset class="fr-fieldset">
+    <legend class="fr-fieldset__legend">Informations descriptives</legend>
+    <div class="fr-fieldset__element">
+      <p>
+        L’adresse saisie ci-dessous sera celle utilisée sur les mandats édités par Aidants Connect.
+      </p>
+    </div>
+
+    <div class="fr-fieldset__element">{% dsfr_form_field form.web_site %}</div>
+    <div class="fr-fieldset__element">{% dsfr_form_field form.mission_description %}</div>
+    <div class="fr-fieldset__element">{% dsfr_form_field form.avg_nb_demarches %}</div>
+  </fieldset>
+
+  <fieldset
+    class="fr-fieldset"
+    data-controller="address-autocomplete"
+    data-address-autocomplete-api-base-url-value="{{ GOUV_ADDRESS_SEARCH_API_BASE_URL }}"
+  >
+    <legend class="fr-fieldset__legend">Informations administratives</legend>
+    <div class="fr-fieldset__element">
+      <p>
+        L’adresse saisie ci-dessous sera celle utilisée sur les mandats édités par Aidants Connect.
+      </p>
+    </div>
+
+    <div
+    >
+      {% include "_address_validatable_mixin.html" with form=form %}
+
+      <div class="fr-fieldset__element">{% dsfr_form_field form.address %}</div>
+      <div class="fr-fieldset__element--inline">
+        {% dsfr_form_field form.zipcode %}
+        {% dsfr_form_field form.city %}
+      </div>
+
+      {{ form.city_insee_code }}
+      {{ form.department_insee_code }}
+
+      {% with errors=form.zipcode.errors|add:form.city.errors %}
+        <div
+          class="fr-grid-row fr-grid-row--gutters zipcode-container"
+        >
+          <div class="fr-col-12 fr-col-md-5">
+            {% dsfr_form_field form.zipcode %}
+          </div>
+          <div class="fr-col-12 fr-col-md-7 ">
+          </div>
+          <div class="fr-col-8 fr-col-md-5">
+            {{ form.city_insee_code }}
+            {{ form.department_insee_code }}
+          </div>
+        </div>
+
+        {% if errors %}
+          <div class="fr-grid-row fr-grid-row--gutters">
+            <div class="errors fr-col-12 fr-col-md-7 fr-col-offset-md-5">{{ errors }}</div>
+          </div>
+        {% endif %}
+      {% endwith %}
+      {% include "layouts/autocomplete.html" %}
+    </div>
+  </fieldset>
+
+  {% mailto recipient=SUPPORT_EMAIL link_text="contactez l’équipe Aidants Connect" as email_link %}
+  {% dsfr_alert content=email_link|strfmt:"Si votre adresse n’est pas reconnue, {}" type="info" extra_classes="fr-alert--sm" %}
+
+  <ul class="fr-btns-group fr-btns-group--inline-md fr-my-6w">
+    <li>
+      <a
+        class="fr-btn fr-btn--secondary"
+        href=""
+      >
+        Revenir à l’étape précédente
+      </a>
+    </li>
+    <li>
+      <input type="submit" class="fr-btn" value="Passer à l’étape suivante">
+    </li>
+  </ul>
+</form>
\ No newline at end of file
diff --git a/aidants_connect_habilitation/templates/organisation_form.html b/aidants_connect_habilitation/templates/organisation_form.html
index 4cfbc0f5..9ebe2fd8 100644
--- a/aidants_connect_habilitation/templates/organisation_form.html
+++ b/aidants_connect_habilitation/templates/organisation_form.html
@@ -13,88 +13,9 @@
     <div class="fr-grid-row fr-grid-row--gutters">
       <div class="fr-col-12 fr-col-md-6">
         {% include "layouts/_breadcrum [...]

2024-11-25 10:10 UTC, christophehenry requested changes

2024-11-25 10:10 UTC, christophehenry commented on aidants_connect_habilitation/templates/organisation_form.html
>          >
Tu peux partir sur un truc comme ça :

```diff
diff --git a/aidants_connect_habilitation/forms.py b/aidants_connect_habilitation/forms.py
index 5b945030..8593778c 100644
--- a/aidants_connect_habilitation/forms.py
+++ b/aidants_connect_habilitation/forms.py
@@ -17,6 +17,7 @@ from django.forms import (
     TextInput,
     TypedChoiceField,
     modelformset_factory,
+    Media,
 )
 from django.forms.formsets import MAX_NUM_FORM_COUNT, TOTAL_FORM_COUNT
 from django.urls import reverse
@@ -34,8 +35,10 @@ from aidants_connect_common.forms import (
     PatchedErrorList,
     PatchedForm,
     PatchedModelForm,
+    WidgetAttrMixin,
 )
 from aidants_connect_common.utils.gouv_address_api import Address, search_adresses
+from aidants_connect_common.widgets import JSModulePath
 from aidants_connect_habilitation import models
 from aidants_connect_habilitation.models import (
     AidantRequest,
@@ -47,7 +50,7 @@ from aidants_connect_habilitation.models import (
 from aidants_connect_web.models import OrganisationType
 
 
-class AddressValidatableMixin(Form):
+class AddressValidatableMixin(Form, WidgetAttrMixin):
     DEFAULT_CHOICE = "DEFAULT"
 
     # Necessary so dynamically setting properties
@@ -198,9 +201,9 @@ class IssuerForm(ModelForm, CleanEmailMixin, DsfrBaseForm):
         exclude = ["issuer_id", "email_verified"]
 
 
-class OrganisationRequestForm(
-    DsfrBaseForm, AddressValidatableMixin, CleanZipCodeMixin
-):
+class OrganisationRequestForm(DsfrBaseForm, AddressValidatableMixin, CleanZipCodeMixin):
+    template_name = "aidants_connect_habilitation/forms/organisation-request.html"
+
     type = ChoiceField(
         required=True, choices=RequestOriginConstants.choices, label="Type de structure"
     )
@@ -248,29 +251,9 @@ class OrganisationRequestForm(
         required=False,
     )
 
-    def __init__(self, *args, **kwargs):
-        super().__init__(*args, **kwargs)
-        self.widget_attrs(
-            "type",
-            {
-                "data-action": "change->dynamic-form#onTypeChange",
-                "data-dynamic-form-target": "typeInput",
-            },
-        )
-        self.widget_attrs(
-            "is_private_org",
-            {
-                "data-action": "change->dynamic-form#onIsPrivateOrgChange",
-                "data-dynamic-form-target": "privateOrgInput",
-            },
-        )
-        self.widget_attrs(
-            "france_services_label",
-            {
-                "data-action": "change->dynamic-form#onFranceServicesChange",
-                "data-dynamic-form-target": "franceServicesInput",
-            },
-        )
+    @property
+    def media(self):
+        return Media(js=(JSModulePath("js/organisation-form.mjs"),))
 
     def clean_type(self):
         return OrganisationType.objects.get(pk=int(self.data["type"]))
diff --git a/aidants_connect_habilitation/templates/aidants_connect_habilitation/forms/organisation-request.html b/aidants_connect_habilitation/templates/aidants_connect_habilitation/forms/organisation-request.html
new file mode 100644
index 00000000..7508bfe8
--- /dev/null
+++ b/aidants_connect_habilitation/templates/aidants_connect_habilitation/forms/organisation-request.html
@@ -0,0 +1,119 @@
+{% load ac_common %}
+{% load dsfr_tags widget_tweaks %}
+<form
+  method="post"
+  class="fr-my-8v"
+  data-controller="dynamic-form"
+  data-dynamic-form-type-other-value="{{ type_other_value }}"
+>
+  {% csrf_token %}
+
+  <fieldset class="fr-fieldset">
+    <legend class="fr-fieldset__legend">Informations générales</legend>
+    <div class="fr-fieldset__element">
+      <p>Vous pouvez faire autant de demandes qu’il existe de structures d’accueil.</p>
+    </div>
+
+    <div class="fr-fieldset__element">
+      {% dsfr_form_field form.type|attr:"data-action:change->dynamic-form#onTypeChange"|attr:"data-dynamic-form-target:typeInput" %}
+    </div>
+
+    <div class="fr-fieldset__element" data-dynamic-form-target="typeOtherInputContainer">
+      {% dsfr_form_field form.type_other %}
+    </div>
+
+    <div class="fr-fieldset__element">{% dsfr_form_field form.france_services_label|attr:"data-action:change->dynamic-form#onFranceServicesChange"|attr:"data-dynamic-form-target:franceServicesInput" %}</div>
+    <div class="fr-fieldset__element">{% dsfr_form_field form.name %}</div>
+    <div class="fr-fieldset__element">{% dsfr_form_field form.siret %}</div>
+
+    <p>
+      <em>Besoin d’aide pour retrouver votre SIRET ?</em>
+      <a
+        class="fr-link fr-link--icon-right fr-icon-arrow-right-line"
+        href="https://annuaire-entreprises.data.gouv.fr/?mtm_campaign=aidants_connect"
+      >
+        Annuaire des Entreprises
+      </a>
+    </p>
+  </fieldset>
+
+  <fieldset class="fr-fieldset">
+    <legend class="fr-fieldset__legend">Informations descriptives</legend>
+    <div class="fr-fieldset__element">
+      <p>
+        L’adresse saisie ci-dessous sera celle utilisée sur les mandats édités par Aidants Connect.
+      </p>
+    </div>
+
+    <div class="fr-fieldset__element">{% dsfr_form_field form.web_site %}</div>
+    <div class="fr-fieldset__element">{% dsfr_form_field form.mission_description %}</div>
+    <div class="fr-fieldset__element">{% dsfr_form_field form.avg_nb_demarches %}</div>
+  </fieldset>
+
+  <fieldset
+    class="fr-fieldset"
+    data-controller="address-autocomplete"
+    data-address-autocomplete-api-base-url-value="{{ GOUV_ADDRESS_SEARCH_API_BASE_URL }}"
+  >
+    <legend class="fr-fieldset__legend">Informations administratives</legend>
+    <div class="fr-fieldset__element">
+      <p>
+        L’adresse saisie ci-dessous sera celle utilisée sur les mandats édités par Aidants Connect.
+      </p>
+    </div>
+
+    <div
+    >
+      {% include "_address_validatable_mixin.html" with form=form %}
+
+      <div class="fr-fieldset__element">{% dsfr_form_field form.address %}</div>
+      <div class="fr-fieldset__element--inline">
+        {% dsfr_form_field form.zipcode %}
+        {% dsfr_form_field form.city %}
+      </div>
+
+      {{ form.city_insee_code }}
+      {{ form.department_insee_code }}
+
+      {% with errors=form.zipcode.errors|add:form.city.errors %}
+        <div
+          class="fr-grid-row fr-grid-row--gutters zipcode-container"
+        >
+          <div class="fr-col-12 fr-col-md-5">
+            {% dsfr_form_field form.zipcode %}
+          </div>
+          <div class="fr-col-12 fr-col-md-7 ">
+          </div>
+          <div class="fr-col-8 fr-col-md-5">
+            {{ form.city_insee_code }}
+            {{ form.department_insee_code }}
+          </div>
+        </div>
+
+        {% if errors %}
+          <div class="fr-grid-row fr-grid-row--gutters">
+            <div class="errors fr-col-12 fr-col-md-7 fr-col-offset-md-5">{{ errors }}</div>
+          </div>
+        {% endif %}
+      {% endwith %}
+      {% include "layouts/autocomplete.html" %}
+    </div>
+  </fieldset>
+
+  {% mailto recipient=SUPPORT_EMAIL link_text="contactez l’équipe Aidants Connect" as email_link %}
+  {% dsfr_alert content=email_link|strfmt:"Si votre adresse n’est pas reconnue, {}" type="info" extra_classes="fr-alert--sm" %}
+
+  <ul class="fr-btns-group fr-btns-group--inline-md fr-my-6w">
+    <li>
+      <a
+        class="fr-btn fr-btn--secondary"
+        href=""
+      >
+        Revenir à l’étape précédente
+      </a>
+    </li>
+    <li>
+      <input type="submit" class="fr-btn" value="Passer à l’étape suivante">
+    </li>
+  </ul>
+</form>
\ No newline at end of file
diff --git a/aidants_connect_habilitation/templates/organisation_form.html b/aidants_connect_habilitation/templates/organisation_form.html
index 4cfbc0f5..9ebe2fd8 100644
--- a/aidants_connect_habilitation/templates/organisation_form.html
+++ b/aidants_connect_habilitation/templates/organisation_form.html
@@ -13,88 +13,9 @@
     <div class="fr-grid-row fr-grid-row--gutters">
       <div class="fr-col-12 fr-col-md-6">
         {% include "layouts/_breadcrum [...]

2024-11-27 11:18 UTC, christophehenry requested changes

2024-11-27 11:18 UTC, christophehenry commented on aidants_connect_habilitation/forms.py
> +    PatchedModelForm, DsfrBaseForm, AddressValidatableMixin, CleanZipCodeMixin
```suggestion
    ModelForm, DsfrBaseForm, AddressValidatableMixin, CleanZipCodeMixin
```

2024-11-27 11:18 UTC, christophehenry commented on aidants_connect_habilitation/forms.py
> -    )
Pourquoi ça a sauté ça ? C'est toujours présent dans le modèle. On s'en sert plus ? 
Ping @mrjmad

2024-11-27 15:01 UTC, christophehenry commented on aidants_connect_habilitation/views.py
> +            )
Pourquoi ?

2024-12-02 09:00 UTC, MarjolaineLB commented on aidants_connect_habilitation/forms.py
> -    )
@christophehenry ce n'est plus dans le formulaire des maquettes en tous cas

2024-12-02 09:01 UTC, MarjolaineLB commented on aidants_connect_habilitation/views.py
> +            )
pourquoi quoi ? :)

2024-12-02 09:04 UTC, christophehenry commented on aidants_connect_habilitation/views.py
> +            )
Pourquoi on skip la page personnel si y'a un organisation ?

2024-12-02 09:37 UTC, MarjolaineLB commented on aidants_connect_habilitation/views.py
> +            )
oui c'est une erreur, je voulais retourner à la page de récap si on a déjà une demande en cours (sur le modèle de ce qui a été fait sur la partie demandeur) mais c'est peut être une fausse bonne idée

2024-12-02 09:57 UTC, christophehenry commented on aidants_connect_habilitation/views.py
> +            )
Oui parce qu'on peut revenir sur cette page à tout moment sans avroi validé la demande donc l'existance d'un objet organisation ne garanti pas la validation de la demande. Pour faire comme sur la modification demandeur, il faudrait une vue à part. T'en occupe pas ici, laisse la fonctionnalité comme elle est.

2024-12-02 14:57 UTC, christophehenry commented on aidants_connect_habilitation/templates/organisation_form.html
>  {% endblock extrajs %}
```suggestion
{% block extrajs %}
  <script defer type="module" src="{% static 'js/organisation-form.mjs' %}"></script>
{% endblock extrajs %}
```

2024-12-02 15:47 UTC, christophehenry approved these changes

2024-12-02 16:49 UTC, merged