nouvelle page d'accueil espace référent
betagouv/Aidants_Connect pull request #1464
Opened 2024-12-03 14:55 UTC by MarjolaineLB

## 🌮 Objectif

Nouvelle page d'accueil de l'espace référent

## 🖼️ Images
![image](https://github.com/user-attachments/assets/525903bb-d863-4b36-9fe9-ccb84a80415b)

2024-12-03 15:22 UTC, christophehenry requested changes

2024-12-03 15:22 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_responsable/home.html
> +                  <img class="fr-responsive-img" src="{% static 'images/icons/success.svg' %}" alt="" />
Ces icônes sont déjà embarquées dans [`django-dsfr`](https://github.com/numerique-gouv/django-dsfr/tree/main/dsfr/static/dsfr/dist/artwork/pictograms).

```suggestion
                  <img class="fr-responsive-img" src="{% static 'dsfr/dist/artwork/pictograms/system/success.svg' %}" alt="" />
```

2024-12-03 15:22 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_responsable/home.html
> +                  <img class="fr-responsive-img" src="{% static 'images/icons/avatar.svg' %}" alt="" />
```suggestion
                  <img class="fr-responsive-img" src="{% static 'dsfr/dist/artwork/pictograms/digital/avatar.svg' %}" alt="" />
```

2024-12-03 15:22 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_responsable/home.html
> +                  <img class="fr-responsive-img" src="{% static 'images/icons/system.svg' %}" alt="" />
```suggestion
                  <img class="fr-responsive-img" src="{% static 'dsfr/dist/artwork/pictograms/system/system.svg' %}" alt="" />
```

2024-12-03 15:22 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_responsable/home.html
> +                  <img class="fr-responsive-img" src="{% static 'images/icons/loisirs.svg' %}" alt="" />
```suggestion
                  <img class="fr-responsive-img" src="{% static 'dsfr/dist/artwork/pictograms/environment/human-cooperation.svg' %}" alt="" />
```

2024-12-03 15:22 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_responsable/home.html
> +                  <img class="fr-responsive-img" src="{% static 'images/icons/papiers.svg' %}" alt="" />
```suggestion
                  <img class="fr-responsive-img" src="{% static 'static/dsfr/dist/artwork/pictograms/document/national-identity-card.svg' %}" alt="" />
```

2024-12-03 15:22 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_responsable/home.html
> +                  <img class="fr-responsive-img" src="{% static 'images/icons/mail.svg' %}" alt="" />
```suggestion
                  <img class="fr-responsive-img" src="{% static 'dsfr/dist/artwork/pictograms/digital/mail-send.svg' %}" alt="" />
```

2024-12-03 15:22 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_responsable/home.html
> +                    <a href="mailto:contact@aidantsconnect.beta.gouv.fr">Contacter l'équipe</a>
```suggestion
                    {% mailto AC_CONTACT_EMAIL link_text="Contacter l'équipe" %}
```

2024-12-03 15:22 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_aidant/formation_continue.html
> +        <img class="fr-responsive-img" src="{% static 'images/icons/calendar.svg' %}" alt="" />
```suggestion
        <img class="fr-responsive-img" src="{% static 'dsfr/dist/artwork/pictograms/digital/calendar.svg' %}" alt="" />
```

2024-12-03 15:22 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_aidant/formation_continue.html
> +        <img class="fr-responsive-img" src="{% static 'images/icons/book.svg' %}" alt="" />
```suggestion
        <img class="fr-responsive-img" src="{% static 'dsfr/dist/artwork/pictograms/leisure/book.svg' %}" alt="" />
```

2024-12-03 15:22 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_aidant/formation_continue.html
> +        <img class="fr-responsive-img" src="{% static 'images/icons/justice.svg' %}" alt="" />
Je sais pas lequel c'est. Probablement :
```suggestion
        <img class="fr-responsive-img" src="{% static 'dsfr/dist/artwork/pictograms/institutions/justice.svg' %}" alt="" />
```

2024-12-03 15:23 UTC, christophehenry commented
Si tu peux supprimer tous les SVG que t'as rajouté du coup.

2024-12-03 15:24 UTC, christophehenry requested changes

2024-12-03 15:24 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_responsable/home.html
> +      {% include "aidants_connect_web/espace_aidant/statistics.html" %}
Celui-ci ne semble utilisé qu'ici. Si tu peux rappatrier le code ici et supprimer la partial.

2024-12-03 15:51 UTC, mrjmad approved these changes

2024-12-03 15:56 UTC, christophehenry requested changes

2024-12-03 15:56 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_responsable/home.html
> +                  <img class="fr-responsive-img" src="{% static 'static/dsfr/dist/artwork/pictograms/document/national-identity-card.svg' %}" alt="" />
```suggestion
                  <img class="fr-responsive-img" src="{% static 'dsfr/dist/artwork/pictograms/document/national-identity-card.svg' %}" alt="" />
```

2024-12-03 15:56 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_responsable/home.html
> +                    <a href="#">Gérer les cartes </a>
Il manque le `href` ici.

2024-12-03 15:59 UTC, MarjolaineLB commented on aidants_connect_web/templates/aidants_connect_web/espace_responsable/home.html
> +                    <a href="#">Gérer les cartes </a>
c'est normal, il n'existe pas. 
Le bloc est prêt en avance, il est hidden

2024-12-04 08:44 UTC, christophehenry approved these changes

2024-12-04 08:45 UTC, merged