DSFR sur la page référents
betagouv/Aidants_Connect pull request #1474
Opened 2024-12-12 13:43 UTC by christophehenry

## 🌮 Objectif

DSFR sur la page référents

## 🖼️ Images

![](https://github.com/user-attachments/assets/25f4dcb4-f3f9-4666-80f1-9d29414d01c9)

2024-12-20 11:12 UTC, MarjolaineLB requested changes

2024-12-20 11:12 UTC, MarjolaineLB commented on aidants_connect_habilitation/templates/aidants_connect_habilitation/referent-form-view.html
> +    <h1 class="fr-mb-2v">Formulaire d’habilitation</h1>
```suggestion
    <h1 class="fr-mb-2v">Formulaire d’habilitation</h1>
```
Pour garder une présentation cohérente avec les autres étapes

2024-12-23 13:13 UTC, mrjmad approved these changes

2024-12-23 14:04 UTC, MarjolaineLB approved these changes

2024-12-24 09:21 UTC, merged