Dsfr mon organisation
betagouv/Aidants_Connect pull request #1477
Opened 2024-12-16 16:36 UTC by MarjolaineLB

## 🌮 Objectif

Mise à jour de la page organisation de l'espace référent

## 🔍 Implémentation

- mise en place des tuiles pour les liens vers la gestion des cartes (hidden pour le moment)
- amélioration de la présentation des thématiques activées (formulaire de modification)

## 🏕 Amélioration continue

- amélioration de l'interface des thématiques dans le formulaire de création de mandat

## 🖼️ Images
Page organisation de l'espace référent
![image](https://github.com/user-attachments/assets/43b0e2e5-87c4-46bb-a8b8-4e19dcaf553e)

Formulaire de création de mandat
![image](https://github.com/user-attachments/assets/03c7ec6e-17ab-410a-ae24-446805a5415f)

2024-12-17 07:53 UTC, christophehenry requested changes

2024-12-17 07:53 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_responsable/organisation.html
> +    <p class="fr-tag">Numéro d'habilitation : {{ organisation.data_pass_id }}</p>
```suggestion
    {% if organisation.data_pass_id %}<p class="fr-tag">Numéro d'habilitation : {{ organisation.data_pass_id }}</p>{% endif %}
```

2024-12-17 09:11 UTC, mrjmad approved these changes

2024-12-18 07:53 UTC, christophehenry requested changes

2024-12-18 07:53 UTC, christophehenry commented on aidants_connect_habilitation/templates/issuer_space.html
> +                        {% endif %}
```suggestion
                        <p class="fr-badge fr-badge--new">{{ organisation.get_status_display }}</p>
```

[`Model.get_FOO_display`](https://docs.djangoproject.com/en/5.1/ref/models/instances/#django.db.models.Model.get_FOO_display)

2024-12-18 07:53 UTC, christophehenry commented on aidants_connect_habilitation/templates/issuer_space.html
> +                        {% if organisation.status == "NEW" %}
```suggestion
                        {% if organisation.status == organisation.Status.NEW %}
```

2024-12-23 13:14 UTC, mrjmad approved these changes

2024-12-23 14:08 UTC, christophehenry approved these changes

2024-12-24 09:10 UTC, merged