Utiliser le hash du FC_AS_FI_SECRET
betagouv/Aidants_Connect pull request #252
Opened 2020-11-23 09:27 UTC by mrjmad

## 🌮 Objectif

Utiliser le hash du FC_AS_FI_SECRET et donc ne plus sauvegarder sa valeur

## 🔍 Implémentation

- Ajout d'une nouvelle variable d'environnement, 
- Suppression d'une variable existante
- Modification de la vue "token"

## 🏕 Amélioration continue

## ⚠️ Informations supplémentaires

## 🖼️ Images

2020-11-30 10:50 UTC, Anna-Livia requested changes

2020-11-30 10:50 UTC, Anna-Livia commented on aidants_connect_web/tests/test_views/test_id_provider.py
> +    HASH_FC_AS_FI_SECRET="e26ade3b37d31920d89e233c447b0d5e51accff2fdc51d1f377b031b5d581e70",  # noqa
Pourquoi le "# noqua" ? On pourrai mettre le hash sur plusieurs lignes sans que cela n'affecte le test non ?

2020-11-30 10:50 UTC, Anna-Livia commented on aidants_connect_web/views/id_provider.py
> +    except:  # noqa
Pourquoi ne pas prévoir les cas d'erreurs ? (et donc le # noqa)

2020-11-30 10:50 UTC, Anna-Livia commented on aidants_connect_web/views/id_provider.py
> +    fc_as_ci_client_id = request.POST.get("client_secret")
fc_as_ci_client_id --> ne serait-ce pas plutôt `client_secret` ?

2020-11-30 10:50 UTC, Anna-Livia commented on aidants_connect_web/views/id_provider.py
> +        "client_secret": hash_client_secret,
On pourrait aussi modifier le nom de la clé de dict pour matcher le traitement

2020-11-30 10:50 UTC, Anna-Livia commented on aidants_connect_web/views/id_provider.py
> +        "client_secret": settings.HASH_FC_AS_FI_SECRET,
Pareil ici

2020-12-07 08:29 UTC, Anna-Livia approved these changes
Merci pour cette PR ! :tada:

Dans l'intérêt de l'amélioration continue, dans la description de la PR, sur la partie "implémentation", il aurait été à mon avis interessant d'avoir le nom de l'ancienne variable et le nom de la nouvelle.

2020-12-07 08:37 UTC, Anna-Livia commented
Aussi, je pense que ce serait interessant dans la doc de mettre gun "how to" pour hasher des strings. Qu'en penses-tu ?

2020-12-07 08:55 UTC, mrjmad commented
ok avec les deux commentaires, je le fais avant de la merger. :)

2020-12-16 11:01 UTC, Anna-Livia approved these changes
Merci pour cette PR 🎉 

J'ai fait une mini-remarque sur le readme.
Je te propose une fois mergée de pousser en pp pour tester tout ça :)

2020-12-16 11:12 UTC, merged