Ajoute un formulaire de demande d'aide
betagouv/Aidants_Connect pull request #306
Opened 2021-02-24 10:24 UTC by Lycia-r

## 🌮 Objectif
Donner un moyen simple de contacter l'équipe

## 🔍 Implémentation
Ajoute un bouton à l'espace aidant
Besoin d'aide : création d'un formulaire de demande d'aide

## ⚠️ Informations supplémentaires

_(optionnel) Documentation, commandes à lancer, variables d'environment, etc_

## 🖼️ Images

_(optionnel) Une ou plusieurs captures d'écran_

2021-03-16 13:44 UTC, christophehenry requested changes

2021-03-16 13:44 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/espace_aidant/home.html
> +          <h3>🆘<br>J'ai besoin d'aide</h3>
Je mettrais un `aria-hidden` sur 🆘. Ces caractères ont la fâcheuse tendance à mal passer sur les lecteurs d'écran.

2021-03-16 14:01 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/espace_aidant/home.html
> +          <h3>🆘<br>J'ai besoin d'aide</h3>
Je vais faire la passe sur les 4 éléments de titre, du coup

2021-03-16 14:21 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/espace_aidant/home.html
> +          <h3>🆘<br>J'ai besoin d'aide</h3>
C'est fait !

2021-03-18 08:37 UTC, christophehenry approved these changes

2021-03-18 08:47 UTC, merged