Possibilité de régénérer une attestation passée (partie 1 : support pour les anciennes attestations)
betagouv/Aidants_Connect pull request #319
Opened 2021-03-12 08:53 UTC by christophehenry

## 🌮 Objectif

Ouvre la possibilité de régénérer une attestation qui a été accordée par le passé par un ou une usagère.

## 🔍 Implémentation

- Pour les attenstations antérieures à cette modification, elles seront retrouvées via le journal de log en comparant le hash de tous les templates du projet à celui dans l'entrée du journal.

## 🏕 Amélioration continue

## ⚠️ Informations supplémentaires

## 🖼️ Images

2021-03-12 08:57 UTC, christophehenry commented on aidants_connect_web/views/mandat.py
> +    return HttpResponseNotFound("Pas d'attestation trouvée pour ce mandat")
Me manque plus qu'un template pour ces deux cas d'erreur et ça devrait être bon.

2021-03-12 10:39 UTC, christophehenry commented on aidants_connect_web/views/mandat.py
> +        {"message": "Impossible de récupérer le document original pour ce mandat"},
C'est pas très canonique de mettre du texte directement dans la vue mais à ce que j'ai vu, il n'y a pas d'internationalisation dans le projet et ce n'est pas prévu. Donc pas forcément de soucis ici sur la gestion des messages d'erreur ?

2021-03-14 14:47 UTC, tut-tuuut requested changes
Good job ! Il y a juste cette question de nommage "legacy" qui me chiffonne un peu.

2021-03-14 14:47 UTC, tut-tuuut commented on aidants_connect_web/models.py
> +        template engine (without `templates` prepended`) otherwise
Je ne comprends pas le "otherwise" en fin de commentaire, que voulais-tu dire ?

2021-03-14 14:47 UTC, tut-tuuut commented on aidants_connect_web/models.py
> +    def _get_template_path_legacy(self, aidant: Aidant) -> Union[None, str]:
Je n'aime pas trop ce terme "legacy" dans le titre de la méthode, je préfère que ce soit plus descriptif. Pourquoi pas tout simplement "get_template_path_from_journal_hash" ? C'est plus instructif et ça évitera l'effet "version-finale-v7-finale-avant-validation.doc" si on re-change d'algo plus tard.

2021-03-14 14:47 UTC, tut-tuuut commented on aidants_connect_web/views/mandat.py
> +    return __attestation_visulisation(request, settings.MANDAT_TEMPLATE_PATH)
Il manquerait pas une lettre dans le nom de la fonction ?
```suggestion
    return __attestation_visualisation(request, settings.MANDAT_TEMPLATE_PATH)
```

2021-03-14 14:47 UTC, tut-tuuut commented on aidants_connect_web/views/mandat.py
> +def __attestation_visulisation(request, template: str):
Ici aussi on peut ajouter le petit `a` perdu ! (Sinon kaboum)
```suggestion
def __attestation_visualisation(request, template: str):
```

2021-03-14 14:47 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/mandat_not_found.html
> +    <h1 class="text-red text-center margin-0"><span aria-hidden="true">⚠&nbsp;</span>{{ message }}</h1>
Tu demandais des retours sur les messages d'erreur, voici quelques idées : 
- en titre h1 : juste "une erreur s'est produite lors de l'impression du mandat", et je ne mettrais que le warning en rouge, pas tout le titre. (ça se discute, je dis juste ça parce que je trouve que ce gros cadre rouge ça fait un peu peur, mais pour le coup je ne suis pas UX)
- ensuite des explications et des détails avec des phrases verbales : je préfère éviter les messages laconiques sans point en fin de phrase. (Ces détails peuvent être dans le template, affichés avec un if, on n'est pas obligé de surcharger la view avec des dizaines de lignes de texte) ;
- surtout, un principe de base : ne pas laisser l'utilisateur/trice tout/e seul/e avec son message d'erreur mais lui donner des indications sur sa possibilité d'agir : contacter le support avec un numéro d'erreur, retourner à la liste des mandats…

2021-03-14 14:47 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/mandat_not_found.html
> +    <h1 class="text-red text-center margin-0"><span aria-hidden="true">⚠&nbsp;</span>{{ message }}</h1>
Ah oui c'est ce que tu disais sur le slack : oui pour détailler ce qui se passe et ajouter du log verbeux ! (D'où l'idée du numéro d'erreur qui pourrait être affiché dans le log et à l'utilisateur, pour qu'on retrouve nos petits plus facilement)

2021-03-14 14:47 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/usager_details.html
> -              <a id="view_mandat_attestation" class="button"><span aria-hidden="true">🖨&nbsp;</span>Voir l’attestation (bientôt)</a>
Ça fait TELLEMENT plaisir de virer ce `(bientôt)` 🎉

2021-03-14 14:47 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/usager_details.html
> +              <a id="view_mandat_attestation" class="button" href="{% url 'mandat_visualisation' mandat_id=mandat.id %}"><span aria-hidden="true">🖨&nbsp;</span>Voir l’attestation</a>
Je vois la conversion d'impostrophe en apostrophe, et j'approuve. 👍

2021-03-14 14:47 UTC, tut-tuuut commented on aidants_connect_web/views/mandat.py
> +        {"message": "Impossible de récupérer le document original pour ce mandat"},
En effet on n'a pas du tout de problématique d'internationalisation.
Par contre on pourrait peut-être ajouter un "code" dans ce dict ? Pour pouvoir loguer et aussi faire des if dans le template plus facilement.

2021-03-15 09:04 UTC, christophehenry commented on aidants_connect_web/models.py
> +        template engine (without `templates` prepended`) otherwise
T'as raison, il en manque un bout. Dans le cas contraire, ça renvoie `None`. C'est ça qu'il manque.

2021-03-15 09:07 UTC, christophehenry commented on aidants_connect_web/models.py
> +        template engine (without `templates` prepended`) otherwise
Tu as raison, il en manque un bout. Dans le cas contraire, ça retourne `None`.

2021-03-15 11:11 UTC, christophehenry commented on aidants_connect_web/models.py
> +            aidant__in=mandat.organisation.aidants.all(),
Donc en supprimant l'appel à l'aidant, on se retrouve avec ça. J'avais espéré que l'ORM de Django soit assez intelligent pour le traduire en `LEFT JOIN` mais en vérifiant avec la célèbre Django Debug Toolbar... Non. Cette requête sera bêtement traduite en subquery ce qui est... sous-optimal. Pour rester poli.

J'admet que c'est la première fois que je suis confronté à un join complexe comme celui-là sur Django donc j'ai pas encore trouvé la façon de le faire correctement avec l'ORM (ça doit bien exister !) donc si quelqu'un sait, je veux bien apprendre.

Après, on peut aussi considérer que l'échantillon de données sur lequel on va travailler est, de toutes façons destiné à rester faible (voire à se réduire) donc on peut aussi se contenter d'une requête sous-optimale (d'autant qu'on travaille avec Postgres, ce me semble, qui doit bien intégrer des optims pour ce genre de sous-requêtes mal écrites).

@tut-tuuut @mrjmad, une opinion ?

2021-03-15 14:18 UTC, mrjmad commented on aidants_connect_web/models.py
> +            aidant__in=mandat.organisation.aidants.all(),
je pense que tu peux simplifier en utilisant : 
aidant__organisation=mandat.organisation,

2021-03-16 10:30 UTC, christophehenry commented on .env.example
> -HASH_FC_AS_FI_SECRET=<insert_your_data>
Cette clef apparaissait en double dans le fichier, pas de panique.

2021-03-16 10:31 UTC, christophehenry commented on aidants_connect_web/views/mandat.py
> +    attestation_hash = ""
On peut peut-être discuter d'une autre valeur par défaut à afficher si on retrouve pas le hash original. J'ai mis une chaîne vide mais ça peut-être une autre valeur. Voir même on peut afficher une autre image que le QR code.

2021-03-16 10:57 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/mandat_not_found.html
> +      la base de données. si vous êtes arrivé sur cette pas en suivant un lien donné
```suggestion
      la base de données. Si vous êtes arrivé sur cette page en suivant un lien donné
```

2021-03-16 10:57 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/mandat_not_found.html
> +      Vous pouvez nous envoyer un mail à
```suggestion
      Vous pouvez nous envoyer un e-mail à
```

2021-03-16 10:58 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/mandat_not_found.html
> +    </ul>
Il manque des p'tits bouts

2021-03-16 10:59 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/mandat_not_found.html
> +      par une autre personne — par email ou messagerie instatannée, par exemple — cette
```suggestion
      par une autre personne — par email ou messagerie instatanée, par exemple — cette
```

2021-03-16 11:31 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/mandat_not_found.html
> +    </ul>
J'ai pas fini de travailller mes textes :sweat_smile:

2021-03-17 09:44 UTC, tut-tuuut approved these changes

2021-03-17 12:14 UTC, christophehenry commented on aidants_connect_web/models.py
> +            return journal
**Note :** je viens de rajouter cette partie dans le second commit. Puisque, maintenant, on a l'association entre le journal et le mandat, autant tenter de l'utiliser. Et du coup, si on récupère une et une seule entrée, c'est un hit. Sinon, on utilise l'heuristique habituelle.

2021-03-17 13:38 UTC, mrjmad approved these changes

2021-03-18 11:01 UTC, tut-tuuut approved these changes

2021-03-18 11:19 UTC, mrjmad approved these changes

2021-03-18 11:33 UTC, merged