Ajout d'une commande Django pour notifier les membres d'une organisation des mandats qui vont bientôt expirer
betagouv/Aidants_Connect pull request #329
Opened 2021-03-24 10:50 UTC by christophehenry

## 🌮 Objectif

Ajout d'une commande Django pour notifier les membres d'une organisation des mandats qui vont bientôt expirer

## 🔍 Implémentation

## 🏕 Amélioration continue

## ⚠️ Informations supplémentaires

## 🖼️ Images

2021-03-24 11:03 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/managment/notify_soon_expired_mandates.txt
> +{% endfor %}
J'ai écrit un texte comme ça mais je veux bien l'avis de @Camillefwok dessus.

2021-03-25 09:35 UTC, Camillefwok commented on aidants_connect_web/templates/aidants_connect_web/managment/notify_soon_expired_mandates.txt
> +{% endfor %}
J'ai changé la phrase "vous recevez ce mail pour vous informer que les mandats suivants vont bientôt expirer :" par "L'équipe Aidants Connect vous informe que les mandats suivants vont bientôt expirer"

2021-03-25 09:35 UTC, Camillefwok commented on aidants_connect_web/templates/aidants_connect_web/managment/notify_soon_expired_mandates.txt
> +{% endfor %}
A mon avis, la liste des mandats devrait donner : 
- Usager Full Name
- Date d'expiration du mandat
- Lien vers le mandat en question

2021-03-25 13:22 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/managment/notify_soon_expired_mandates.html
> +          <!-- START CENTERED WHITE CONTAINER -->
En règle générale je préfère éviter de reporter ce genre de commentaire dans le HTML, et utiliser plutôt le commentaire du langage de gabarit : 
```suggestion
          {# START CENTERED WHITE CONTAINER #}
```

Surtout pour du HTML qui se retrouve ensuite dans du webmail.

2021-03-25 13:23 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/managment/notify_soon_expired_mandates.html
> +          <!-- START CENTERED WHITE CONTAINER -->
J'ai juste reprise le template existant mais tu as complètement raison.

2021-03-25 13:26 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/managment/notify_soon_expired_mandates.txt
> +— n° {{ mandate.pk }} réalisé avec {{ mandate.usager.get_full_name }} qui expire le {{ mandate.expiration_date|date:"l j F Y" }}{% if forloop.last %}.{% else %},{% endif %}
Est-ce qu'on affiche usuellement le numéro/ la pk du mandat ? Dans mon souvenir on ne l'utilise nulle part ailleurs, et l'aidant ne fera rien de cette information.

Je serais d'avis de se contenter des infos vraiment utiles pour lui/elle : 
- l'usager,
- la date d'expiration,
- et éventuellement le nombre de périmètres si on les a facilement à cet endroit-là.

2021-03-25 13:47 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/managment/notify_soon_expired_mandates.txt
> +— n° {{ mandate.pk }} réalisé avec {{ mandate.usager.get_full_name }} qui expire le {{ mandate.expiration_date|date:"l j F Y" }}{% if forloop.last %}.{% else %},{% endif %}
Ok pour enlever le numéro du mandat, mais question pratique : comment je commence la phrase, du coup ?
Le nombre de périmètres, c'est les autorisations ?

2021-03-29 14:52 UTC, Camillefwok commented on aidants_connect_web/templates/aidants_connect_web/managment/notify_soon_expired_mandates.txt
> +— n° {{ mandate.pk }} réalisé avec {{ mandate.usager.get_full_name }} qui expire le {{ mandate.expiration_date|date:"l j F Y" }}{% if forloop.last %}.{% else %},{% endif %}
La phrase "L’équipe Aidants Connect vous informe que les mandats suivants vont bientôt expirer" est assez claire, même si on supprime le n° du mandat. Car dans la tête de l'aidant : 1 mandat = 1 usager (mais pas l'inverse). Et oui, le nombre de périmètres = les autorisations. D'ailleurs, plutôt que le nombre de périmètres il est intéressant de nommer les périmètres arrivant à expiration.

2021-03-29 21:53 UTC, mrjmad requested changes

2021-03-29 21:53 UTC, mrjmad commented on aidants_connect_web/tasks.py
> +        recipient_list = [it["email"] for it in organisation.aidants.values("email")]
ici tu peux simplifier en mettant : 
`list(organisation.aidants.values_list("email", flat=True))`

( le list est pas obligatoire du coup, mais je voulais pas changer le type des choses )

2021-03-29 21:53 UTC, mrjmad commented on aidants_connect_web/tasks.py
> +    organisations: List[Organisation] = list(
ici je pense que tu peux simplifier en faisant  : 
`=  list(Organisation.objects.filter(mandats__in=mandates_qset).distinct())`

2021-03-29 21:53 UTC, mrjmad commented on aidants_connect_web/tasks.py
> +            mandates_qset.filter(organisation=organisation).all()
tu as pas besoin de faire le .all() la, le list s'occupe de lancer la requête pour toi

2021-03-30 08:32 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/managment/notify_soon_expired_mandates.txt
> +— n° {{ mandate.pk }} réalisé avec {{ mandate.usager.get_full_name }} qui expire le {{ mandate.expiration_date|date:"l j F Y" }}{% if forloop.last %}.{% else %},{% endif %}
> La phrase "L’équipe Aidants Connect vous informe que les mandats suivants vont bientôt expirer" 

Je parlais du début de chaque item, du coup.

> il est intéressant de nommer les périmètres arrivant à expiration.

La liste des périmètres peut être assez longue, quand-même. Dans le cas où tous les périmètres sont cochés, on pourrait se retrouver avec une longue list entre parenthèses à la fin de l'item. C'est pas forcément top pour la lisibilité, je trouve.

2021-03-30 09:08 UTC, christophehenry commented
Voici le text introduit par les dernières modifications :

> Bonjour,
> 
> L’équipe Aidants Connect vous informe que les mandats suivants vont bientôt expirer :
> 
>   — le mandat réalisé avec xxxxxxxxxxxxxx qui expire le mercredi 9 mars 2022 (6 authorisations),
>     [1] : https://localhost/mandats/2/visualisation ;
> 
>   — le mandat réalisé avec xxxxxxxxxxxxxx qui expire le jeudi 17 mars 2022 (2 authorisations),
>     [2] : https://localhost/mandats/7/visualisation ;
> 
>   — le mandat réalisé avec xxxxxxxxxxxxxx qui expire le mardi 29 mars 2022 (2 authorisations),
>     [3] : https://localhost/mandats/8/visualisation.

2021-03-30 14:24 UTC, Camillefwok reviewed
J'ai peur de tout casser : c'est ok mais il faut juste la petite faute de texte (6 authorisations) -> (6 autorisations) :)

2021-03-30 22:02 UTC, mrjmad approved these changes

2021-03-31 08:19 UTC, merged