Ajoute la notion de responsable structure et d'autorisation à créer des mandats
betagouv/Aidants_Connect pull request #342
Opened 2021-04-13 12:09 UTC by tut-tuuut

## 🌮 Objectif

Poser les bases du modèle de responsable structure, qui peut : 

- être responsable de plusieurs organisations ;
- ne pas avoir un rôle d'aidant professionnel dans la structure.

## 🔍 Implémentation

- Relation N-N entre `Aidant` et `Organisation`
- Getters et décorateurs relatifs à la responsabilité envers les structures à la possibilité de créer des mandats
- Ajout de garde-fous empêchant des responsables qui ne sont pas officiellement aidants de créer des mandats et d'effectuer des démarches à la place des usagers.

## 🏕 Amélioration continue

J'ai fermé un `div` qui était resté ouvert sur la page de FC as FI.

2021-04-14 07:15 UTC, christophehenry commented on aidants_connect_web/models.py
> +    responsable_de = models.ManyToManyField(Organisation, related_name="responsables")
Un aidant peut être responsable de plusieurs structures ? :thinking:

2021-04-14 07:16 UTC, mrjmad approved these changes

2021-04-14 07:19 UTC, christophehenry requested changes
Un commentaire général : peut-être que les migrations pourraient être rassemblées dans un même fichier ?

2021-04-14 07:19 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/usager_details.html
> +        <a id="add_mandat" class="button float-right" href="{% url 'new_mandat' %}">📝&nbsp;Créer un mandat</a>
```suggestion
        <a id="add_mandat" class="button float-right" href="{% url 'new_mandat' %}">
            <span aria-hidden="true">📝&nbsp;</span>Créer un mandat
        </a>
```

2021-04-21 13:19 UTC, tut-tuuut commented
@christophehenry j'ai fusionné les migrations, comme suggéré, je merge la PR

2021-04-21 13:19 UTC, merged