Mise en place d'un renouvellement de mandat
betagouv/Aidants_Connect pull request #348
Opened 2021-04-28 10:38 UTC by mrjmad

## 🌮 Objectif

Pouvoir renouveler des mandats sans repasser par une connexion France Connect. Mise en place de la possibilité de renouvellement sur la liste des usagers ayant un mandat valide ou expiré

## 🔍 Implémentation

L'objet Connection est un objet central sur la création du mandat utilisé pour passer des infos entre chaque étape. Ma première tentative visait à faire un processus de renouvellement sans objet connexion et donc totalement décorrélé des choses actuelles. Mais cela aboutissait a beaucoup beaucoup trop de rajout de ligne de code. Du coup j'ai finalement décidé de coller au plus proche de l'existant en créant un objet Connection qui simle une connection FC même si elle n'a pas lieu. 

Cela me permet du coup de me brancher sur le dispositif actuel. J'ai légèrement modifié le formulaire de l'étape 1 du mandat pour pouvoir le réutiliser en en dérivant et en changeant simplement son titre et l'input de soumission qui ne renvoie plus sur France Connect mais envoie directement à l'étape suivante. Cela permettra de ne pas à avoir à gérer 2 formulaires quasi identiques en parallèle. (Typiquement entre le début de ma PR et la fin, l'ajout du numéro de téléphone a été mis en place et du coup le renouvellement de mandat gagne cette fonctionnalité de manière automatique ). 

## 🏕 Amélioration continue

- _(optionnel) Une liste d'autres modifications pas en lien direct avec la PR_

## ⚠️ Informations supplémentaires

_(optionnel) Documentation, commandes à lancer, variables d'environment, etc_

## 🖼️ Images

![image](https://user-images.githubusercontent.com/354064/116390660-98255200-a81e-11eb-92b0-d1f1d6c704ba.png)

2021-04-28 11:47 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/new_mandat/renew_mandat.html
> +{% block title %}Aidants Connect - Renouveller un mandat{% endblock %}
```suggestion
{% block title %}Aidants Connect - Renouveler un mandat{% endblock %}
```

2021-04-28 11:48 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/new_mandat/renew_mandat.html
> +          <h2 class="step-title">Étape 3 : Renouveler le  mandant</h2>
Tu veux renouveler le mand*ant* ou tu veux renouveler le mand*at* ?

2021-04-28 11:48 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/new_mandat/renew_mandat.html
> +          <input id="submit_button" type="submit" class="button" value="Renouveler le  mandant" />
Idem ici il y a écrit "mandant" j'imaginais plutôt "mandat".

2021-04-28 11:53 UTC, tut-tuuut approved these changes
Je trouve ça plutôt élégant comme solution ! OK pour moi modulo les coquilles orthographiques.

2021-04-28 12:50 UTC, christophehenry commented on aidants_connect_web/views/renew_mandat.py
> +                access_token=get_random_string(150, allowed_chars),
Pourquoi t'as pas réutilisé [la même méthode que dans `aidants_connect_web/views/id_provider.py`](https://github.com/betagouv/Aidants_Connect/blob/main/aidants_connect_web/views/id_provider.py#L308) ici, du coup ? :thinking:

2021-04-28 13:03 UTC, christophehenry approved these changes

2021-04-28 13:15 UTC, christophehenry commented
Question : si tu renouvelles un mandat actif, ça a l'air d'invalider le mandat en cours mais je vois pas quel morceau de code fait ça :thinking:

2021-04-28 13:17 UTC, christophehenry requested changes

2021-04-28 13:17 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/new_mandat/renew_mandat.html
> +          <input id="submit_button" type="submit" class="button" value="Renouveler le  mandant" />
Et y'a aussi un petit soucis de CSS sur ce bouton, ici :

![](https://user-images.githubusercontent.com/22097904/116410131-c3b33700-a834-11eb-994f-0b78eef17c4e.png)

2021-04-28 13:17 UTC, christophehenry commented on aidants_connect_web/views/renew_mandat.py
> +            return redirect("new_mandat_recap")
Peut-être que ça vaudrait le coup de mettre une petit entrée dans le journal concernant cette action ?

2021-04-28 15:02 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/new_mandat/renew_mandat.html
> +          <input id="submit_button" type="submit" class="button" value="Renouveler le  mandant" />
Est-ce que tu as le même pb de CSS après un ctrl-F5 ?

2021-04-28 15:36 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/new_mandat/renew_mandat.html
> +          <input id="submit_button" type="submit" class="button" value="Renouveler le  mandant" />
Ouip. Moi j'ai un `padding: 0;` sur `#submit_button`.

2021-04-28 22:00 UTC, mrjmad commented on aidants_connect_web/views/renew_mandat.py
> +                access_token=get_random_string(150, allowed_chars),
parce que je l'ai vu à un moment, que je l'ai ensuite oublié et que du coup j'ai reécrit un truc de mon coté :)

2021-04-28 22:28 UTC, mrjmad commented
> Question : si tu renouvelles un mandat actif, ça a l'air d'invalider le mandat en cours mais je vois pas quel morceau de code fait ça thinking
> 

j'ai vérifié dans le code, et c'est même documenté par un commentaire ici :  
https://github.com/betagouv/Aidants_Connect/blob/bb3a1aed7fbcda2eb6bb765e983db7dd04188741/aidants_connect_web/views/mandat.py#L149 

a la réflexion ça a du sens fonctionnellement, cela permet d'avoir à tout instant un seul mandat valide pour une démarche précise.  

C'est d'ailleurs déjà le cas en production quand un nouveau mandat est généré pour un usager qui a déjà un mandat valide.

2021-04-28 22:54 UTC, mrjmad commented
voila j'ai : 
- pris en compte les fix typo 
- ajouté une entrée de log
- corrigé le CSS 
- repris la méthode classique pour le calcul acces token

ca me semble bon pour une finale review :)

2021-04-29 08:40 UTC, christophehenry approved these changes

2021-05-04 14:29 UTC, merged