Séparation d'une carte AC et d'un compte aidant
betagouv/Aidants_Connect pull request #385
Opened 2021-06-21 10:45 UTC by tut-tuuut

## 🌮 Objectif

Permettre au responsable structure de "séparer" la carte AC du compte d'un aidant (en cas de perte, erreur, problème technique…)

## 🔍 Implémentation

- Un petit formulaire sur la page "aidant" (c'est un peu caché pour éviter les fausses manips) ;
- Le responsable saisit la raison qui les pousse à séparer la carte du compte ;
- Ça fait la double manip en base de données et ça insère une entrée de journal.

## 🏕 Amélioration continue

- On ajoute aussi des entrées de journal pour l'association carte/aidant et pour la validation d'une carte.
- On remet les info de monitoring (nombre de mandats) réclamées par certains respo structure.

## 🖼️ Images

Emplacement du formulaire dépliable sur la page aidants : 

![Capture d’écran 2021-06-21 à 12 36 33](https://user-images.githubusercontent.com/1035145/122749973-3ddcc680-d28e-11eb-8bec-3270b81771b6.png)

Aspect du formulaire déplié : 

![Capture d’écran 2021-06-21 à 12 36 40](https://user-images.githubusercontent.com/1035145/122750035-51882d00-d28e-11eb-9102-c725ee793726.png)

Les différentes raisons possibles : 
![Capture d’écran 2021-06-21 à 12 36 57](https://user-images.githubusercontent.com/1035145/122750059-5b119500-d28e-11eb-82ed-424976ba359c.png)

Après la suppression de la carte : 

![Capture d’écran 2021-06-21 à 12 37 15](https://user-images.githubusercontent.com/1035145/122750083-6238a300-d28e-11eb-98c3-0680e0f366f0.png)

Dans le journal : 

![Capture d’écran 2021-06-21 à 12 38 51](https://user-images.githubusercontent.com/1035145/122750114-6bc20b00-d28e-11eb-9ff3-52e9666028cf.png)

![Capture d’écran 2021-06-21 à 12 39 01](https://user-images.githubusercontent.com/1035145/122750155-79779080-d28e-11eb-894e-cb0bad4ba660.png)

2021-06-21 12:33 UTC, christophehenry commented on aidants_connect_web/views/espace_responsable.py
> +    if request.method == "POST":
Perso, je ferais plutôt l'inverse, ici:

```suggestion
    if request.method == "GET":
        return render(
            request,
            "aidants_connect_web/espace_responsable/aidant.html",
            {"aidant": aidant, "organisation": organisation, "form": form},
        )

    form = RemoveCardFromAidantForm(request.POST)
    # etc.
```

L'interêt, c'est surtout sortir du code le plus rapidement possible sur les chemins de code les plus cours pour améliorer la lisibilité. Comme ça, tu te retrouves pas avec un énorme bloc de code sous le `if`.

Je rajouterais aussi `@require_http_methods(["GET", "POST"])` sur la function pour bien noter qu'il n'y a pas d'autre chemin possible que `GET` et `POST`.

2021-06-21 12:33 UTC, christophehenry commented on aidants_connect_web/views/espace_responsable.py
> +                )
Pourquoi un `transaction.atomic()` ici ? :thinking:

2021-06-21 13:05 UTC, tut-tuuut commented on aidants_connect_web/views/espace_responsable.py
> +                )
Modification du TOTP + ajout de l'entrée de journal. Je ne veux pas que l'un se passe sans l'autre.

2021-06-21 13:21 UTC, christophehenry commented on aidants_connect_web/views/espace_responsable.py
> +                )
Ok, je vois.

2021-06-21 13:26 UTC, tut-tuuut commented on aidants_connect_web/views/espace_responsable.py
> +    if request.method == "POST":
Oui tu as raison, return early et évitons ces gros blocs if.
Mais en termes de lisibilité, je crois que je préférerais surtout une méthode `dissociateCard`, je l'ai cherchée ce matin après une semaine loin de ce code. :)

2021-06-22 13:16 UTC, tut-tuuut commented
Les tests sont en échec parce que : le test de validation TOTP. Je place beaucoup d'espoir en #386.

2021-06-29 12:41 UTC, christophehenry requested changes

2021-06-29 12:41 UTC, christophehenry commented on aidants_connect_web/views/espace_responsable.py
> +@require_http_methods(["GET"])
```suggestion
@require_GET
```

2021-06-29 12:41 UTC, christophehenry commented on aidants_connect_web/views/espace_responsable.py
> +@require_http_methods(["GET"])
```suggestion
@require_GET
```

2021-06-29 14:00 UTC, tut-tuuut commented on aidants_connect_web/views/espace_responsable.py
> +@require_http_methods(["GET"])
Cool, c'est vrai que c'est plus léger ! Je l'ai pris en compte dans mon commit b7abffe :)

2021-06-29 14:01 UTC, tut-tuuut commented on aidants_connect_web/views/espace_responsable.py
> +    if request.method == "POST":
Update : c'est fait

2021-06-29 14:30 UTC, christophehenry commented on aidants_connect_web/views/espace_responsable.py
> +        )
C'est pas forcément ouf comme méthode de gestion d'erreur de juste mettre un message générique. Ici, l'utilisateur ou l'utilisatrice va juste se dire « bon, ok, y'a eu une erreur, et donc ? Je fais quoi ? ». D'autant plus que tu affiches ça que si le formulaire est invalide. Est-ce que ça a une chance d'arriver ? A priori, si j'ai bien compris, c'est juste un menu déroulant permettant de sélectionner la raison de la séparation. Donc pas de raison que le formulaire soit invalide. Dans l'éventuel improbable cas où ça arriverait, moi, je jetterais une erreur serveur pour bien que tout le monde soit au courant qu'il y a vraiment un truc bizarre qui vient de se passer.

2021-07-01 07:24 UTC, tut-tuuut commented on aidants_connect_web/views/espace_responsable.py
> +        )
OK bonne idée, ça donne quelque chose comme ça : https://sentry.io/organizations/betagouv-f7/issues/2484482056/?project=5707861

2021-07-01 08:42 UTC, christophehenry requested changes

2021-07-01 08:42 UTC, christophehenry commented on aidants_connect_web/views/espace_responsable.py
> +    if form.is_valid():
```suggestion
    if not form.is_valid():
        raise Exception("Invalid form for card/aidant dissociation")
    ...
```

2021-07-01 14:37 UTC, tut-tuuut commented on aidants_connect_web/views/espace_responsable.py
> +    if form.is_valid():
On va y arriver :D

2021-07-01 14:47 UTC, christophehenry approved these changes

2021-07-01 16:04 UTC, tut-tuuut commented
Merci pour l'approbation, je merge ça demain matin pour bien commencer mon vendredi. 🎉

2021-07-02 09:21 UTC, merged