Update contenu mandat
betagouv/Aidants_Connect pull request #429
Opened 2021-09-20 13:32 UTC by Camillefwok

## 🌮 Objectif

Ajouter les mentions RGPD dans le mandat

## 🔍 Implémentation

Ajout de deux phrases : 
1. Pour que XXXXX puisse agir à ma place: [...]
« Les aidants habilités par [Nom de la structure] doivent : […] 
**Je reconnais que l’aidant habilité m’a informé des droits dont je dispose, prévus par les articles 13 à 22 du Règlement général sur la protection des données (RGPD)**
2. « Les aidants habilités par [Nom de la structure] doivent : […] 
**-	s’assurer que l’information a été réalisée de manière concise, transparente, compréhensible et aisément accessible conformément aux dispositions de l’article 12 du RGPD.** 

## ⚠️ Informations supplémentaires

S'assurer que le mandat reste sur une page

2021-09-20 13:36 UTC, Camillefwok commented
Il faudrait aussi ajouter (en encart ?) : 
"Le délégué à la protection des données de l'Agence Nationale de la Cohésion des Territoires peut également être contacté par courriel à l’adresse : dpo@anct.gouv.f et par courrier à l’adresse :
Agence Nationale de la Cohésion des Territoires
A l'attention du délégué à la protection des données (DPD)
20 avenue de Ségur
75007 Paris"

2021-09-21 09:41 UTC, christophehenry requested changes

2021-09-21 09:41 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/mandat_templates/20200511_mandat.html
> +      <li>prendre toutes les précautions pour assurer la sécurité de mes informations personnelles ;
```suggestion
      <li>prendre toutes les précautions pour assurer la sécurité de mes informations personnelles ;
```

2021-09-21 09:41 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/mandat_templates/20200511_mandat.html
> +      <li>prendre toutes les précautions pour assurer la sécurité de mes informations personnelles ;
(Espace insécable)

2021-09-22 14:05 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/new_mandat/new_mandat_recap.html
>                {% endif %}
On est d'accord que c'était à l'envers, là ?

2021-09-22 15:49 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/new_mandat/new_mandat_recap.html
>                {% endif %}
Oui, ça semble plus logique comme ça :thinking:

2021-10-01 14:59 UTC, tut-tuuut commented on aidants_connect_web/static/css/attestation.css
> +        display: block; /* page-break-before won't work if body is in display:flex */
PI le `body` est en `display:flex;` partout ailleurs sur le site à cause de `main.css`. Ça empêchait firefox de prendre en compte l'instruction `page-break-before`.

2021-11-18 09:38 UTC, christophehenry commented
Pas d'avancée sur cette PR. On clôt. On pourra réouvrir au besoin.

2021-11-18 09:38 UTC, closed without merging