Masquer le bouton renouveler si tout les mandats d'un usager sont explicitement révoqués
betagouv/Aidants_Connect pull request #503
Opened 2022-01-19 15:33 UTC by liviaribeiro

## 🌮 Objectif
Masquer le bouton renouveler si tout les mandats d'un usager sont explicitement révoqués

## 🔍 Implémentation
Ajout de la fonction all_revoked_mandats qui retourne True se tous les mandats d'un usager sont révoqués. Changement dans le template usager_row pour cacher le bouton "Renouveler le mandat"

2022-01-20 08:45 UTC, christophehenry requested changes

2022-01-20 08:45 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/usagers/usagers.html
> +              {% include "aidants_connect_web/usagers/usager_row.html" with usager=usager with_valid_mandate=False%}
```suggestion
              {% include "aidants_connect_web/usagers/usager_row.html" with usager=usager with_valid_mandate=False %}
```

2022-01-20 08:45 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/usagers/usager_row.html
> +  {% endif %}
```suggestion
  {% if not usager.all_revoked_mandats %}
  <td><a href="{% url 'renew_mandat' usager_id=usager.id %}">Renouveler le mandat</a></td>
  {% endif %}
```

2022-01-20 08:45 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/usagers/usager_row.html
> +  {% endif %}
Pas forcémment besoin de mettre une balise vide dans le cas où tous les mandats ont été révoqués explicitement.

2022-01-20 08:45 UTC, christophehenry commented on aidants_connect_web/models.py
> +    def all_revoked_mandats(self):
On peut peut-être trouver un meilleur nom ? Celui-là me donne l'impression qu'il renvoie la liste de tous les mandats révoqués. Par contre, j'ai pas d'idées.

2022-01-20 08:51 UTC, christophehenry commented
Un petit test d'intégration pour montrer que le bouton n'est pas généré dans le cas où les mandats ont tous été explicitement révoqués, ce serait bien en plus. Les tests d'intégration pour cette partie du code sont [ici](https://github.com/betagouv/Aidants_Connect/blob/main/aidants_connect_web/tests/test_functional/test_usagers.py), je crois. Tu peux t'inspirer de [ce morceau de code](https://github.com/betagouv/Aidants_Connect/blob/main/aidants_connect_web/tests/test_functional/test_remove_aidant_from_organisation.py#L86-L89) pour t'assurer qu'un élément HTML est bien absent de la page.

2022-01-20 08:52 UTC, tut-tuuut commented on aidants_connect_web/models.py
> +    def all_revoked_mandats(self):
```suggestion
    def has_all_mandats_revoked(self):
```

?

2022-01-20 08:52 UTC, tut-tuuut commented on aidants_connect_web/models.py
> +    def all_revoked_mandats(self):
Astuce pour nommer des booléens : regarder si on peut trouver un nom en `has_xx` ou `is_xx` :)

2022-01-20 08:58 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/usagers/usager_row.html
> +  {% endif %}
Si on avait d'autres cellules après dans la ligne du tableau, il faudrait laisser la cellule vide pour ne pas décaler.
Là ça se discute, l'absence de la cellule fait lever un avertissement dans le validateur HTML.

2022-01-20 09:03 UTC, tut-tuuut commented on aidants_connect_web/templates/aidants_connect_web/usagers/usagers.html
> +              {% include "aidants_connect_web/usagers/usager_row.html" with usager=usager with_valid_mandate=False%}
Comme black ne regarde que les fichiers .py et que j'aime pas ajouter moi-même les espaces, j'ai pris l'habitude de reformater automatiquement mes templates avec le raccourci cmd-alt-L de Pycharm.

2022-01-20 09:12 UTC, tut-tuuut commented
Je module ce que dit Christophe, tu n'as pas besoin de sortir les tests Selenium pour vérifier la présence ou non d'un bouton. Mais oui en effet ça manque d'un test. :)

[Ici par exemple](https://github.com/betagouv/Aidants_Connect/blob/main/aidants_connect_web/tests/test_views/test_mandat.py#L620-L637) on se contente d'un `get` avec le client Django de base et on regarde si certains textes donnés sont présents dans le contenu de la réponse.

2022-01-20 09:15 UTC, christophehenry commented on aidants_connect_web/templates/aidants_connect_web/usagers/usager_row.html
> +  {% endif %}
Ah oui, suis-je bête. J'ai pas remarqué que c'était une cellule de tableau.

J'ai rien dit !

2022-01-24 22:46 UTC, mrjmad approved these changes
ça m'a l'air très bien. Une remarque très perso. J'aurais plus "remonter" les tests vers la partie "test unitaires". 

je m'explique j'aurais testé tout les cas, unitairement de "has_all_mandats_revoked_or_expired_over_a_year" uniquement ( en testant True ou False) et du coup un seul test ( genre pour quand tout est révoqué ) en mode intégration . 

Mais c'est une préférence perso. 

Je pense que c'est bien parti pour un premier merge dans le projet, si @tut-tuuut et @christophehenry valident ! :)

2022-01-25 07:42 UTC, tut-tuuut approved these changes

2022-01-25 08:47 UTC, christophehenry approved these changes

2022-01-25 13:22 UTC, merged