Mise à jour de la dépendance factory boy
betagouv/Aidants_Connect pull request #517
Opened 2022-01-26 16:19 UTC by christophehenry

## 🌮 Objectif

Mise à jour tricky. Ça casse des trucs. En particulier [des chemins d'imports qui changent](https://github.com/FactoryBoy/factory_boy/blob/master/docs/changelog.rst#breaking-changes). Du coup, j'ai décider de faire sauter l'import global de `factory` et importer au cas par cas.

2022-01-26 16:22 UTC, christophehenry commented on aidants_connect_habilitation/tests/factories.py
> +        phone = Faker("phone_number").evaluate(None, None, {"locale": "fr_FR"})
Celui-ci est particulièrement relou. La nouvelle méthode a une signature probablement plus logique pour son utilisation en interne mais pas pour son utilisation publique.

2022-01-27 08:05 UTC, tut-tuuut commented on requirements.txt
> +flake8==4.0.1
Pourquoi on a une MAJ majeure de flake8 dans la même PR ? C'est voulu ou c'est un accident de squash ?

Si tu dépends d'une autre modif qui est actuellement dans une autre PR, tu peux faire une branche à part pour les nouvelles modifs, et créer une PR qui n'aurait pas la branche "main" pour base mais ta première PR. Comme ça on ne voit que les modifs intéressantes. Je ne sais pas si c'est très clair. Je peux t'expliquer en dessinant si besoin. :)

2022-01-27 08:16 UTC, tut-tuuut requested changes
Je ne sais pas si je suis très rassurée par les breaking changes dans `factory` mais à la limite je peux m'en accommoder en faisant des copier-coller, comme d'habitude.

Ce qui m'embête davantage c'est le mélange entre cette PR et #516, ainsi que la modif sur flake8 dont je ne sais pas d'où elle sort. En l'état je ne suis pas sereine pour merge cette PR.

Tu peux commencer par rebase cette branche sur celle de #516 pour bien séparer les sujets. Pour le sujet flake8, selon si c'est nécessaire pour factory boy ou pas on le laisse ici ou pas, mais là comme je ne comprends pas et je ne suis pas rassurée.

2022-01-27 08:41 UTC, christophehenry commented on requirements.txt
> +flake8==4.0.1
Ah c'est un accident, ça. À la base, j'avais prévu de mettre à jour qu'une poignée de dépendances majeures de test mais celle de `factory-boy` s'est révéle plus compliquée que prévu.

2022-01-27 08:43 UTC, christophehenry commented
C'est fait. À la base, j'avais prévu de mettre à jour qu'une poignée de dépendances majeures de test mais celle de `factory-boy` s'est révélée plus compliquée que prévu.

2022-01-27 08:51 UTC, christophehenry commented
Ok, y'a un problème, ici : les tests disent que tout passe sur la CI mais moi, ils sont cassés en local. Quelqu'un d'autre peut confirmer ? @tut-tuuut, @mrjmad, @liviaribeiro ?

2022-01-27 09:43 UTC, tut-tuuut approved these changes

2022-01-27 13:48 UTC, merged