update-faq-juridique
betagouv/Aidants_Connect pull request #529
Opened 2022-02-03 13:52 UTC by matteo-goracci

## 🌮 Objectif

Actualiser la section mandat de la FAQ Aidants Connect pour des raisons juridiques.

## 🔍 Implémentation

- modification du point : "Comment l’usager·ère signe-t-il ou signe-t-elle le mandat ?"

2022-02-03 14:48 UTC, Camillefwok requested changes
Il manque juste un é à "mandat créé" ;)

2022-02-03 14:51 UTC, Camillefwok approved these changes

2022-02-04 09:36 UTC, tut-tuuut commented on aidants_connect_web/templates/public_website/faq/mandat.html
>            <li>Après chaque validation, Aidant Connect crée une empreinte numérique unique (appelée «&nbsp;Hash&nbsp;») qui permet de garantir l’intégrité du mandat, c’est-à-dire le fait que le docume
- Je pense surtout que le premier point devrait avoir une majuscule, si c'est le mélange majuscules/minuscules qui t'embête. :)
- La deuxième étape je la nommerais plutôt "Le recueil du consentement", non ?
- Côté HTML, plutôt que des textnode et des `<p>` qui se baladent dans des `<li>`, soit on assume et on fait des titres `<hx>` (mais j'ai un doute sur la validité du truc à l'intérieur d'un `<li>`, soit on introduit chaque élément de la liste par un simple mot suivi de `:`.

```suggestion
      <ol>
          <li>Identification : blablabla.</li>
          <li>Recueil du consentement : blablabla.</li>
          <li>Validation : blablabla</li>
      </ol>
```

2022-02-04 09:58 UTC, tut-tuuut commented
Je clôture celle-ci, voir #530 à la place :)

2022-02-04 09:58 UTC, closed without merging