Import résultats PIX et ajout dans mail hebdomadaire
betagouv/Aidants_Connect pull request #644
Opened 2022-05-10 14:01 UTC by liviaribeiro

## 🌮 Objectif
Import automatique tous les soirs des test PIX réalisés la veille.

## 🔍 Implémentation
Import résultats PIX depuis metabase; mise à jour colonnes test_pix et date_test_pix dans table aidants à former (habilitation requests); ajout dans le mail hebdomadaire

## 🏕 Amélioration continue

- _(optionnel) Une liste d'autres modifications pas en lien direct avec la PR_

## ⚠️ Informations supplémentaires

_(optionnel) Documentation, commandes à lancer, variables d'environment, etc_

## 🖼️ Images

_(optionnel) Une ou plusieurs captures d'écran_

2022-05-10 14:04 UTC, liviaribeiro commented on aidants_connect_web/models.py
> +    test_pix = models.BooleanField("Test PIX", default=False)
J'ai commencé par le plus simple : actualiser la table aidants à former et ignorer ceux dont on ne retrouve pas le mail. On pourra faire ça en deuxième temps.

2022-05-10 14:05 UTC, liviaribeiro commented on aidants_connect_web/models.py
> +    date_test_pix = models.DateTimeField("Date test PIX", null=True, blank=True)
J'ai commencé par le plus simple : actualiser la table aidants à former et ignorer ceux dont on ne retrouve pas le mail. On pourra faire ça en deuxième temps.

2022-05-11 09:21 UTC, christophehenry commented on aidants_connect_habilitation/tasks.py
> +    json_result = cli.cards.download(card_id="5166", format="json")
`"5166"` d'où provint cet ID ? Ça pourrait valloir le coup d'en faire une variable d'env.

2022-05-11 09:26 UTC, christophehenry requested changes

2022-05-11 09:26 UTC, christophehenry commented on aidants_connect_web/models.py
> +    test_pix = models.BooleanField("Test PIX", default=False)
Cette propriété, elle correspond à quoi ? Elle indique si la personne a eu le test ? Si oui, je préfèrerais `test_pix_passed`, que je trouve plus parlant.

2022-05-11 12:25 UTC, liviaribeiro commented on aidants_connect_habilitation/tasks.py
> +    json_result = cli.cards.download(card_id="5166", format="json")
c'est l'ID de la question sur metabase

2022-05-17 13:30 UTC, mrjmad approved these changes

2022-05-18 09:01 UTC, merged