Ajout du modèle de données pour la traduction de mandats
betagouv/Aidants_Connect pull request #799
Opened 2023-02-08 15:52 UTC by christophehenry

## 🌮 Objectif

Ajout du modèle de données pour la traduction de mandats

2023-02-08 15:53 UTC, christophehenry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Modélisation base de données des traductions de mandat](https://trello.com/c/2ut79wNk/148-mod%C3%A9lisation-base-de-donn%C3%A9es-des-traductions-de-mandat)

2023-02-08 15:59 UTC, christophehenry commented on aidants_connect_pico_cms/admin.py
> +        widgets = {"lang": SearchableRadioSelect}
Petite explication, ici : je préfère proposer toutes les langues supportées dans Dajngo et afficher un widget qui permet la recherche de langues. Ça fait moins de travail côté dev et moins de travail pour les bizdev qui n'ont pas besoin d'ajouter un enregistrement pour chaque langue.

2023-02-08 18:58 UTC, mrjmad requested changes
il faut trouver une solution pour le Dari / les prochaines langues qui ne seront pas dans les langues supportées par django

2023-02-08 18:58 UTC, mrjmad commented on aidants_connect_pico_cms/admin.py
> +        widgets = {"lang": SearchableRadioSelect}
le problème c'est que des langues des mandats seront peut etre pas dans les langues supportées par django. 

et on a le problème la déjà, l'une des traductions étant le Dari et il n'est pas dans les langues supportées par django.

2023-02-09 09:01 UTC, christophehenry commented
> le problème c'est que des langues des mandats seront peut etre pas dans les langues supportées par django.

Dans ce cas, , [il suffira de les rajouter là](https://github.com/betagouv/Aidants_Connect/pull/799/files#diff-62bc8737f3403de42aa4ea5180164f79a36b70e52c9d8cd9aa6684a8ced6feb1R250-R257), ce que j'ai déjà fait pour le pachtoune. Je vais rajouter le Dari en plus dans cette PR.

2023-02-09 13:26 UTC, mrjmad commented
> > le problème c'est que des langues des mandats seront peut etre pas dans les langues supportées par django.
> 
> Dans ce cas, , [il suffira de les rajouter là](https://github.com/betagouv/Aidants_Connect/pull/799/files#diff-62bc8737f3403de42aa4ea5180164f79a36b70e52c9d8cd9aa6684a8ced6feb1R250-R257), ce que j'ai déjà fait pour le pachtoune. Je vais rajouter le Dari en plus dans cette PR.


effectivement. 

du coup on "annule" quand même le pourquoi du pico cms a savoir l'autonomie des bizdev sur la redaction de contenu ...

2023-02-09 15:07 UTC, mrjmad approved these changes

2023-02-09 15:58 UTC, merged