update readme
betagouv/Aidants_Connect pull request #826
Opened 2023-03-10 09:25 UTC by rebeccadumazert

## 🌮 Objectif

Mieux expliciter les étapes du `README.md ` afin que l'installation du projet soit plus simple.

2023-03-13 20:47 UTC, mrjmad commented on README.md
> +brew install pipenv
je sais que juste au dessus on utilise brew pour pg, mais en disant que c'est juste un exemple, du coup on pourrait ici mettre les deux possibilité a savoir brew ou pip install pipenv? 

d'ailleurs j'ai une question, brew à l'interieur d'un venv il fait bien ce qu'on lui demande ?  installer dans le venv ?

2023-03-16 11:17 UTC, christophehenry commented
C'est normal que cette PR soit encore en brouillon ? Y'a encore des choses à ajouter ?

2023-04-12 07:59 UTC, christophehenry requested changes

2023-04-12 07:59 UTC, christophehenry commented on README.md
> +brew install pipenv
```suggestion
brew install pipenv  # Sur Mac
# Ou
pip install pipenv
```

2023-04-12 07:59 UTC, christophehenry commented on README.md
> +brew install pipenv
@mrjmad Je propose cette modif et on merge ?

2023-04-12 08:47 UTC, merged