Supression de la page succès de création de mandat
betagouv/Aidants_Connect pull request #957
Opened 2023-07-11 09:51 UTC by christophehenry

## 🌮 Objectif

Supression de la page succès de création de mandat. À la fin de la création de mandat, le processus redirige maintenant directement vers la page de mandat final.

## 🖼️ Images

![](https://github.com/betagouv/Aidants_Connect/assets/22097904/4091bcc5-4d14-4ccf-9f98-96f219f90c88)
![](https://github.com/betagouv/Aidants_Connect/assets/22097904/92cc1ef0-fb4c-41db-bcac-204615628a84)

2023-07-11 09:52 UTC, christophehenry commented
![](https://github.trello.services/images/mini-trello-icon.png) [Mandat Final](https://trello.com/c/HF03HQ61/297-mandat-final)

2023-07-11 23:00 UTC, mrjmad requested changes
il manque le nouveau titre + chapeau rouge sur la nouvelle page : 
"Mandat Final"
"le mandat a été créé .... "

2023-07-12 08:49 UTC, christophehenry commented
Bien vu. C'est corrigé.

2023-07-12 19:44 UTC, mrjmad approved these changes

2023-07-13 08:08 UTC, merged